preactjs/preact-www

content/guide/differences-to-react.md
Basic batching was folded into React a while ago, so `setState` is now async and queues up changes for the next batch run. One less API difference!
=> Remove setState not being async

content/guide/forms.md
Thing is, this example still doesn't work. The `input` would seem to ignore the value of `checked` when it's updated. Tested in the REPL. [Failing example here](https://preactjs.com/repl?code=export%20default%20class%20Foo%20extends%20Component%20%7B%0A%09render(%7B%20%7D%2C%20%7B%20results%3D%5B%5D%20%7D)%20%7B%0A%09%09return%20(%0A%09%09%09%3Cdiv%3E%0A%09%09%09%09%3Ch1%20style%3D%22text-align%3Acenter%3B%22%3ECheckbox%3C%2Fh1%3E%0A%09%09%09%09%3CMyForm%20%2F%3E%0A%09%09%09%3C%2Fdiv%3E%0A%09%09)%3B%0A%09%7D%0A%7D%0A%0A%0Aclass%20MyForm%20extends%20Component%20%7B%0A%20%20%20%20toggle(e)%20%7B%0A%20%20%20%20%20%20%20%20e.preventDefault()%3B%20%20%20%2F%2F%20we%27ll%20handle%20this%2C%20thanks%0A%20%20%20%20%20%20%20%20let%20checked%20%3D%20!this.state.checked%3B%0A%20%20%20%20%20%20%20%20t …
=> Fix example syntax

src/components/logo.js
In order for the ellipse animation's stroke-dasharray trick to work seamlessly, the dasharray needs to sum to exactly the circumference of your ellipse.  Here's a close-up GIF of the problem:
you can see the strokes glitching where the gaps will close pretty tight before the other end catches up.
Anyway, I did a little math and with the help of [this Wolfram search](http://www.wolframalpha.com/input/?i=ellipse+a%3D196+b%3D75+circumference) and I've got it spinning seamlessly.
Hope it's :smile:!
=> fixed logo ellipse stroke gaps

src/components/header/index.js, src/components/logo.js
This solves #23 by pausing animations in the header except when the mouse is hovering over that menu item.
=> header animations only on hover; fixes #23

content/guide/differences-to-react.md
In order to clarify the difference between React's SyntheticEvent system and Preact's event system, add footnote to "Synthetic Events" to explain Preact's usage of `addEventListener`.
=> Address preact #377

content/about/libraries-addons.md
This adds a link to [preact-i18nline](https://github.com/download/preact-i18nline), an integration of Preact with the [i18n-js](https://rubygems.org/gems/i18n-js/versions/2.1.2) ecosystem that came out of Ruby but also enjoys moderate popularity on Node.
=> Adds a link to preact-i18nline

src/lib/default-language.js
When a user configures the following languages in their browser:
`navigator.languages === ["en-US", "en", "de-DE", "de", "zh-TW", "zh"]`
the page currently renders in Chinese, although English should take precedence.
This PR changes that behaviour and makes sure the order of languages is respected by including English in the detection (instead of only falling back to English if no matching localisation is found).
=> Improve user language detection

src/components/header/style.less
header gets re-painted on the main thread every time you scroll, which affects scroll performance.
=> Promote fixed header to GPU

content/about/demos-examples.md
Connectivity Index is a Preact-powered site, and as such I feel it may be a good addition to the examples page. :) Also uses preact-render-to-string to generate server side markup.
=> Added Connectivity Index to the examples page.

src/components/footer/index.js
Steps to reproduce:
1. Open https://preactjs.com/
2. Navigate to any docs page, say **Getting Started**
3. Click **Edit this Page** link in the footer
4. You’re editing the home page (actually the first page after site was first loaded)
=> Fix edit link in the footer after navigation to another page

content/index.md
The second paragraph in the **Big Performance** section on https://preactjs.com/ currently reads:
> It even includes extra performance features like customizable update batching, optional async rendering, DOM recycling and optimized event handling via Linked State.
The features “customizable update batching” and “optional async rendering” contain broken links that lead to 404 pages. This PR removes them, so the paragraph is simpler and contains a link to the valid guide for Linked State.
=> Remove dead links in Big Performance section

content/guide/getting-started.md, content/guide/lifecycle-methods.md, content/lang/es/guide/getting-started.md, content/lang/es/guide/lifecycle-methods.md, content/lang/pt-br/guide/getting-started.md, content/lang/pt-br/guide/lifecycle-methods.md, content/lang/zh/guide/getting-started.md, content/lang/zh/guide/lifecycle-methods.md
removing the the non-standard lifecycle method  `componentDidUnmount()` from the docs.
=> remove componentDidUnmount() lifecycle method

content/guide/differences-to-react.md, content/lang/es/guide/differences-to-react.md, content/lang/pt-br/guide/differences-to-react.md, content/lang/zh/guide/differences-to-react.md
Remove this description from the docs, since it no longer exists in Preact 8
Related to #126
=> remove objects as class from the docs

content/guide/differences-to-react.md
Since linkstate is now a separate module, it is no longer part of the Preact module and therefore doesn't really belong in this list.
=> Remove Linked State from the "What's Added?" list

content/lang/zh/guide/linked-state.md
dot-notated keypath 原来翻译中翻译为点式路径（也就是对象中的多层级属性foo.bar.a），想不到更好的翻译，继续沿用了，但是总感觉这种翻译还是不好理解，会有更好的翻译吗？
=> update linked-state in zh docs

content/guide/getting-started.md
You should use [text](URL) for links in markdown.
=> Fix broken link

content/guide/getting-started.md
Saw that while reviewing the french version. We didn't change the API in Babel 7.
=> Add Babel 7 version in getting-started

content/about/we-are-using.md
As mentioned in developit/preact#991 the companies Domain changed to https://andcards.com/
* [Old website in google cache](http://webcache.googleusercontent.com/search?q=cache:9bWzF1YN9DEJ:try.cards/).
* [New company website](https://andcards.com/)
=> Update URL for Company "cards" to andcards.com

src/components/header/index.js, src/components/header/style.less
Change from svg component and rotate to prevent open collective link from covering page fixing #200. I tried to match the existing corner link as close as possible while using css to rotate to prevent the link from blocking underlying areas on the page.
**Before (SVG)**
**After (CSS)**
**Pixelmatch (Diff)**
No more blocking!
=> Change Open Collective Logo to use CSS

content/guide/differences-to-react.md
Resolves [#1167](https://github.com/developit/preact/issues/1167), clarifying support for old React Context API rather than the new API.
=> Update context api documentation

content/guide/differences-to-react.md
Just changed 'an' to 'a' which seems more appropriate.
=> Small grammar correction in differences-to-react guide.

content/guide/getting-started.md
As a new user it was an odd experience opening the boilerplate to be told to use the CLI. I felt it made more sense to just update the link to point to the cli and not the boilerplate.
=> getting-started.md - Change preact boilerplate to preact cli

content/about/demos-examples.md
BitMidi is powered by Preact! This PR adds the website [BitMidi](https://bitmidi.com) to the list of demo sites.
Website screenshot: 
Context about the site:
BitMidi is a historical archive of MIDI files from the early web era. It's a fun way to experience the early web aesthetic of Geocities and Angelfire sites, and also a powerful tool for musicians to find "song stems" to use as the basis for song remixes. It uses the latest modern web technology including WebAssembly and Web Audio to bring MIDI back to life.
=> Add BitMidi to list of demo sites

content/about/libraries-addons.md
It's now possible to create a storybook environment specifically for Preact components (https://www.npmjs.com/package/@storybook/preact). I'm not entirely sure under which sub-heading to put it, but I felt it belonged most with the GUI Toolkits.
=> Add @storybook/preact to libraries-addons

src/components/header/index.js, src/components/header/style.less
=> new mobile menu

content/guide/api-reference.md, src/style/index.less, src/style/markdown.less, src/style/variables.less
This PR makes minor changes to the css to make our site easier to read.
- Increase font size from `15px` to `16px`. It's not much but makes the font easier to read on my screen.
- Increase `h2` size to make it easier to scan for the eyes
- Change text link styles to be more upbeat and visually more distinct from their surroundings
- Make blockquotes more visually appealing by using colors. This better differentiates them from the body text and hints to the user in a visual way that it may contain some useful information
The changes are best illustrated via a screenshot.
Before:
After:
=> Minor Design UX improvements

src/pwa.js
Not all browsers support Service-Workers, so this PR checks for them before trying to use them. I've run into this in my local dev setup which doesn't use https.
=> Check if browser supports SW before using them

src/components/controllers/page/index.js, src/components/controllers/page/style.less, src/components/controllers/page/table-of-content.js, src/components/controllers/page/table-of-contents.less, src/components/footer/style.less, src/components/header/style.less, src/style/markdown.less, src/style/mixins.less, src/style/variables.less
This PR completely rewrites the table of contents area. It's now always visible on the left and will highlight the current heading. On mobile it's moved behind a toggle on the lower right corner of the screen. On top of that I slightly modified the heading styles and made all link colors use our brand color.
=> Make table of contents always visible

src/components/header/index.js
The same issue is present on our current live site. Looks like nobody tested on Firefox :sweat_smile: See these screenshots:
before:
after:
=> Fix word wrapping in donate corner

src/components/header/search.js
This simplifies the searchBox setup and allows it to be prerendered, which prevents a fairly costly relayout in the header.
=> Fix prerendering for search

package-lock.json, package.json, src/components/github-stars.js, src/components/header/gh-version.js, src/lib/request.js, test/browser/homepage.test.js, test/jest-puppeteer.config.js
This PR fixes all the weird test failures on my machine. There were several issues with our setup:
- One test ran before all scripts are loaded
- Code coverage always included external resources like google analytics
- Code coverage sometimes contains duplicate coverage information for the same resource (not sure why)
- We didn't wait for the server to boot up completely before starting our test suite (one **must** set the `port` option for `jest-puppeteer`. Only found that buried in a GitHub issue)
- Upgrade `puppeteer` + `jest-puppeteer` (just to be sure)
- We didn't caught errors when any of the requests to the GitHub API failed
=> Fix CI flakyness

src/components/controllers/page/index.js, src/components/edit-button/index.js, src/components/edit-button/style.less, src/components/footer/index.js
This PR moves the `"Edit this Page"` button to where users will actually see it. Previously it was placed in the footer where it was easy to miss. FWIW: I didn't know we had such a feature before working on the docs site :sweat_smile:
=> Move "edit this page" button next to page title

.github/size-plugin.yml
By default [bot](https://github.com/kuldeepkeshwar/size-plugin-bot), assumes a commit results in a single build and look for a single stats to do its own stuff(comment on pr or update on push).
In case, a commit results in multiple builds ( e.g srr + browser) producing multiple stats, we can help [bot](https://github.com/kuldeepkeshwar/size-plugin-bot) with a configuration to understand the situation better 😊 and do its stuff more effectively 🙃
=> add configuration file for size-plugin bot

src/components/code-block.js, src/lib/prism.js
Optimize Prism by removing all DOM code, which avoids it inadvertently running against preact-rendered DOM on the client. Technically there's a `Prism.manual` option for this, but it doesn't work with bundlers and doesn't strip out the ~1kb of DOM code.
=> Optimize Prism.js 

preact.config.js
- Each rule must be an item in the array.
- Add `content/` rewrite rule to make it serve `.md` files
=> Fix netlify redirects

src/components/app.js, src/components/doc-version/index.js, src/components/header/gh-version.js
This PR appends `(current)` or `(next)` in the documentation dropdown depending on the latest GitHub release. It's a little nicer than having to do it manually :tada:
=> Dynamically label versions based on GitHub release

content/en/guide/v10/api-reference.md, preact.config.js, src/_redirects, src/components/controllers/page/index.js, src/components/controllers/page/style.less, src/components/edit-button/index.js, src/components/edit-button/style.less, src/style/index.less
This PR improves a few little things:
- Add `min-height` for content area so that it doesn't jump around that much
- Make "Missing Translation" box look more informing rather than an error
- Add more spacing around edit button on mobile so that it doesn't overlap the page title
- Content: Remove duplicate lifecycle section
- Redirects: Move all redirects into `_redirects` instead of having some in `preact.config.js` (my bad, sry)
=> Add more polishing

content/en/guide/v10/unit-testing-with-enzyme.md
This PR updates the Enzyme testing documentation for Preact v10 to use the "official" Preact adapter (enzyme-adapter-preact-pure). The new guide mostly applies to Preact 8 as well, although the examples will need to be different since the v10 guide uses an example with hooks. I will look at updating the Preact v8 docs separately.
Changes in detail:
- Update the Enzyme testing documentation to recommend the
enzyme-adapter-preact-pure package which is part of the Preact project.
It is easier to set up and avoids several of the limitations of the
previous adapter.
- Expand the into to explain what Enzyme is in a little more detail, how
it supports different React versions and React-like libraries and the
different execution environments (browser with Karma, Node with jsdom)
it supports
- …
=> Update Enzyme testing documentation for Preact v10

content/en/guide/v8/unit-testing-with-enzyme.md
Update the Enzyme testing docs for Preact v8 to be the same as the
new Preact v10 docs (see https://github.com/preactjs/preact-www/pull/374), except for the following changes:
- The example component's implementation uses the class API
(`Component`) rather than hooks (which is v10-only). The tests
are unchanged.
- Remove references to the `act` function which does not exist in
Preact v8. Since Preact v8 doesn't have effect hooks, it is
sufficient to call `wrapper.update()` to flush state updates
- Replace references to "state updates and effects" with just "state updates" since that is the only type of async update in Preact v8
=> Update the Enzyme testing docs for Preact v8

src/components/app.js, src/components/doc-version/index.js, src/components/header/gh-version.js
Pulling from GitHub leads to wrong results because of different release
lines. We don't really gain much by having this dynamic anyway.
=> Make doc "current" label static.

content/en/guide/v10/components.md, content/en/guide/v10/context.md, content/en/guide/v10/differences-to-react.md, content/en/guide/v10/getting-started.md, content/en/guide/v10/hooks.md, content/en/guide/v10/linked-state.md, content/en/guide/v10/refs.md, content/en/guide/v10/server-side-rendering.md, content/en/guide/v10/switching-to-preact.md, content/en/guide/v10/tutorial.md, content/en/guide/v10/upgrade-guide.md
Correct a few spelling errors in English Preact v10 content and cases where
acronyms were not capitalized.
=> Fix a few spelling errors in English Preact v10 content

content/en/guide/v10/refs.md
The first example for `createRef` in the guide incorrectly uses nonexistent method `setRef` instead of `this.ref`
=> Fix References createRef docs example

content/de/index.md, content/en/guide/v10/differences-to-react.md, content/en/guide/v10/switching-to-preact.md, content/en/index.md, content/es/index.md, content/fr/index.md, content/it/index.md, content/pt-br/index.md, content/tr/index.md, content/zh/index.md, src/style/index.less
This PR rewrites the page about `preact/compat` or otherwise known as `Switching to Preact`. That was the last page which still referenced `preact-compat`.
=> Rewrite compat page

content/en/guide/v10/whats-new.md
Div tag was closed prematurely, which also resulted in a non-functioning
example, when run in REPL.
=> Fix typo in CSS Custom Properties example

content/en/guide/v10/tutorial.md
- Update relative URL to preact-cli page
- URL was missing `/` character from the beginning, causing missing page error
=> fix(tutorial): update relative URL to preact-cli

content/en/guide/v10/context.md
Should be pub-sub instead of pup-sub
=> Fix typo in en/guide/v10/context.md

content/en/guide/v10/api-reference.md
We've got a few reports for incorrectly passed values in the past week. This should make it more clear what's allowed and what not.
=> Add section about type of first arg to render()

content/en/guide/v10/api-reference.md
- Added missing quote to hydrate example:
`document.getElementById('container)` -> `document.getElementById('container')`
- Changed import from `render` to `hydrate` considering example context.
=> Updated Hydrate Example

content/en/guide/v10/upgrade-guide.md
Clear up some misconceptions regarding how Preact X `render` method works.
Perhaps once we spec up how the `replaceNode` parameter works in Preact X, we can add that here as a migration path.
Here are some codepens demonstrating the various behaviors:
Preact 8: https://codepen.io/andrewiggins/pen/KKKEmpq
Preact X: https://codepen.io/andrewiggins/pen/rNNRmev
React 16: https://codepen.io/andrewiggins/pen/GRRemOZ
=> Improve docs on how Preact X render method works

content/en/cli.md
There are other links missing from [`/about/cli.md`](https://raw.githubusercontent.com/preactjs/preact-www/43ccc139116cd8b0387263186da3c4f280dc699c/content/en/about/cli.md), but this one stood out.
=> fix: add Lighthouse score proof link

content/en/guide/v10/refs.md, content/pt-br/guide/v10/refs.md
In the "Putting it all together" example, the return statement opening
parenthesis has been closed with a curly braces making the example
producing an error while in REPL.
=> Fix wrong curly brace in References section

content/en/guide/v10/hooks.md
The documentation here was just inaccurate - hooks are not functional (since they are impure functions).
To demonstrate how hooks are not pure functions, consider how the arguments to `useState(1)` do not determine the return value. The returned val can change render to render even though the arguments do not.
=> Removing inaccurate description of hooks

content/en/index.md
> Markdown isn't supported within HTML blocks
I'm not sure whether this is actually correct/desirable, so haven't adjusted any other languages
=> Fix code markup on landing page

content/pt-br/index.md
The phrase "closer to the DOM" was mistranslated to "mais proximo do metal" (closer to the metal)
=> [fixed] wrong word 'metal' on pt-br

src/components/controllers/page/index.js, src/components/controllers/page/style.less, src/components/doc-version/index.js
We've gotten a few messages on slacks or PRs that were made against the older version instead of the current docs. This PR adds a banner on old docs pointing users to the newest version.
=> Add warning banner on old docs

content/en/guide/v10/hooks.md
I believe the semicolon was placed in error and was intended to be a comma.
=> Replace Semi-Colon with Comma

content/en/guide/v10/server-side-rendering.md
We're using a separate renderer for JSX.
=> Fix wrong jsx option in render-to-string docs

content/en/guide/v10/getting-started.md
From [Jest documentation](https://jestjs.io/docs/en/configuration.html#modulenamemapper-objectstring-string):
> Note: If you provide module name without boundaries ^$ it may cause hard to spot errors. E.g. relay will replace all modules which contain relay as a substring in its name: relay, react-relay and graphql-relay will all be pointed to your stub.
=> Correct code for Aliasing in Jest

content/en/guide/v10/debugging.md
- replace extension store link
- replace devtools homepage link
- remove reference about trying it on Preact website since debug mode seems stripped from build or not enabled
=> Update docs to reference Preact Devtools over React Developer Tools

content/en/guide/v10/options.md
Return value of `Options.event()` replaces event of event handler.
Therefore,  `Options.event()`  returns value.
https://github.com/preactjs/preact/blob/9038db5f6aa4d0e1203bc4a9f6423a4dcbf46962/src/diff/props.js#L160
https://github.com/preactjs/preact/pull/2381
=> Fix options.event description

content/en/guide/v10/differences-to-react.md
Mentioned on Twitter: https://mobile.twitter.com/runjep/status/1234832873598922752
Replace `and` with `or`.
=> Fix incorrect Purecomponent description

src/components/we-are-using/index.js, src/components/we-are-using/style.less
- Fix bad logo contrast in dark mode, thanks to some luminosity based grayscale wizardry I'm told @mathiasbynens is the one to thank for this trick :slightly_smiling_face: 
- Remove company names to make the grid appear less "noisy" visually.
Also played around with removing the `opacity: 0.5` on the logos, but without that the logos themselves introduce to many hard edges. It makes it harder (at least for me) to find a single thing to focus on, on the page. 
Before:
After:
=> Fix bad contrast of company logos in dark mode

content/de/guide/v8/progressive-web-apps.md, content/en/guide/v8/progressive-web-apps.md, content/es/guide/v8/progressive-web-apps.md, content/fr/guide/v8/progressive-web-apps.md, content/pt-br/guide/v8/progressive-web-apps.md, content/tr/guide/v8/progressive-web-apps.md, content/zh/guide/v8/progressive-web-apps.md
The code splitting link
`https://webpack.github.io/docs/code-splitting.html` doesn’t exist
anymore. The new link is `https://webpack.js.org/guides/code-splitting/`
=> Fix Webpack code splitting link in v8 progressive web apps section

content/en/cli/getting-started.md, content/es/cli/getting-started.md, content/pt-br/cli/getting-started.md
The existing instruction to run the `start` script does not work as no
such script exists in "package.json".
=> Fix instructions to start dev server

content/en/guide/v10/getting-started.md, content/pt-br/guide/v10/getting-started.md
Minor change in the CLI documentation : 'npm start' should be replaced by 'npm run dev'
=> Updating pt-br  and en version of getting started

content/en/guide/v10/getting-started.md
These additions to the documentation are to address a few gotchas that I encountered while setting up preact/compat with rollup and typescript.  The goal is to share what I learned with the wider audience of preact users so that preact/compat has a bit less of a curve to set up with typescript.
=> add docs for typescript preact/compat and rollup alias

content/en/guide/v10/upgrade-guide.md
It is been over a year since Preact 10.0.0-alpha.0 was released.
I think this sentence may be unnecessary.
=> Remove sentence for LegacyComponent

content/en/guide/v10/context.md, content/pt-br/guide/v10/context.md
The link to the useContext hook currently is set to `#context`, but should be `#usecontext`.
I also noticed that routing does not handle anchors correctly, i.e. the link `https://preactjs.com/guide/v10/hooks#usecontext` works when the page is initially loaded, but does not jump to the anchor after client side navigation happened (tested in Chrome and Firefox). Do you want me to create a ticket for that?
=> fix link to #usecontext hook

content/en/guide/v10/getting-started.md
As suggested in chat, including a component helps point out the syntax difference between JSX and HTM.
=> Update HTM example

content/en/about/libraries-addons.md
👋 Hello there! This includes a link to CapacitorJS in the Libraries and Add-ons. 
Capacitor is a tool that can let developers take their preact app and create native ios and native android apps, without having to change anything to their code. 
We have a dedicated example page in our docs that covers how to enabled this in a preact app, but figured it would make sense to include this in preacts docs as well. 
Cheers 🍻
=> Add Capacitor to the add-ons

src/components/controllers/page/sidebar-nav.js, src/components/controllers/page/sidebar.less
- Stretch over header (easier to use on smaller devices with limited screen space)
- Close it automatically when clicking a link.
=> Mobile: Enhancements to sidebar nav

content/en/cli.md
This replaces `sw-precache` to `Workbox` in `content/en/cli.md`.
=> sw-precache -> Workbox

content/en/guide/v10/preact-testing-library.md, src/config.json
This PR adds a new page for `@testing-library/preact` to the docs.
Probably needs a second read through to get rid of typos/weird sounding sentences. Wrote it down in a single sitting late in the evening 😅
=> Add testing page for @testing-library/preact

content/en/guide/v10/upgrade-guide.md
Moved the ++ to the front of counter variables.
=> Fix bug in v10 upgrade guide example.

src/components/code-editor/style.less
- Lint error message box background color for better contrast ratio and added padding.
- Code error highlighting to underline instead of background color for better legibility.
Fixes #528
=> Update lint error styles

content/en/guide/v10/options.md, src/config.json
There are `Options`, `Option Hooks` and `Renderer Options`. 
IMHO, I think it is better to be unified into `Option Hooks`.
=> Renderer Options -> Option Hooks

content/en/guide/v10/web-components.md
I think `complementary` is correct, not `complimentary`.
=> Fix typo in web-components.md

src/components/code-block/index.js, src/components/jumbotron/style.less, src/style/index.less
In the code blocks, the `Run in Repl` button did not stay fixed in top right corner while horizontally scrolling. This is especially more noticeable on mobile devices.
A container `<div>` was added to the code block with some style refactoring to keep the `Run in REPL` button fixed at the top right corner even while horizontally scrolling. From my tests, it is not breaking other code blocks (I may be wrong though)
Fixes #530
=> Fix 'Run in REPL' not fixed while scrolling

src/style/markdown.less
When navigating to page sections, the selected headline is hidden by the header bar.
This PR adds a `:target` selector with some extra padding on top to keep them visible.
Example: **useState** https://preactjs.com/guide/v10/hooks/#usestate
without `:target` padding
with `:target` padding
=> Add padding top to active link targets (headlines)

content/en/guide/v10/api-reference.md
Since `children` is not always an array.
=> Fix content/en/guide/v10/api-reference.md

content/en/guide/v10/getting-started.md
Snowpack defines its own specific aliasing system which must be configued to use with preact/compat.
=> Adds config to use preact/compat with Snowpack

content/en/guide/v10/typescript.md
I think it is necessary to pass `props` to `super()` in constructor of `Component` class.
=> Fix example in content/en/guide/v10/typescript.md

src/components/header/gh-version.js
I opened the site in my browser today and got confused when I saw a version number from last year in the header, turns out I had JS turned off.
=> Update the current release version in header.

content/en/guide/v10/differences-to-react.md
Just putting this little gotcha out somewhere obvious, as this [Synthetic Event](https://reactjs.org/docs/events.html#mouse-events) sent me down a little rabbit hole today.
Interestingly, `onDoubleClick` _works_ on Safari 14 (but obviously not Chrome).
Using the [Native Event Handler](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/ondblclick) seems like the most sensible  cross-browser solution.
=> Add a note to use DblClick when not using compat

content/en/guide/v10/web-components.md
Fixed typos
```
registerElement -> register
Foo -> TextSection
<slot name=""> -> <span slot="">
```
=> Fixed typos in web components example

src/components/controllers/page/sidebar.less
Currently the header gets slightly stuck behind the side bar. Go to https://preactjs.com/guide/v10/getting-started/ and then scroll down a bit. You won't be able to click on the PreactJS logo to go back to the home page as it's technically layered behind the side bar.
To fix this, I just took a chunk out of the side bar's z-index. This doesn't seem to conflict with anything and is probably the simplest solution. The [header's z-index is 500](https://github.com/preactjs/preact-www/blob/master/src/components/header/style.less#L11) so this will now be below it, as intended.
=> fix: Sidebar z-index

content/en/guide/v10/web-components.md
Replace closing `</slot>` tag with `</span>`
=> Fixed typo in web-components slot example

README.md
I've added a static Slack badge to the README since the current badge is broken. Shields.io allows you to customize the label, message, color, and logo using their badge generator, so this is just one option to consider.
Badge url: https://img.shields.io/badge/slack-Preact%20Slack%20Community-blue?logo=slack
Badge generator: https://shields.io/
Fixes https://github.com/preactjs/preact-www/issues/725
=> fixes Slack README badge

content/en/guide/v10/getting-started.md
Globally installing packages is not necessary at all and can lead to weird permission issues depending on where the global install directory is. This is a friction point for new users (we just got a report on slack). So this PR rewrites that to point to the local installation instead.
=> Remove global install instructions

src/lib/content.js
Fixes two sets of cases:
1. Sections with `/`
* Example: TS preact/compat on [Getting Started](https://preactjs.com/guide/v10/getting-started)
* The Issue: Link in ToC would be to `#typescript-preact/compat-configuration` when the element had an ID of `typescript-preactcompat-configuration`
* Solution: Strip `/` from ToC links
2. Sections with `&`
* Example: Controlled & uncontrolled components on [Forms](https://preactjs.com/guide/v10/forms)
* The issue: Link in ToC would be to `#controlled-uncontrolled-components` when the element had an ID of `controlled--uncontrolled-components`
* Solution: Strip `&` from ToC links only after the spaces have been substituted for hyphens
=> fix: Correcting incorrect table of contents link generation

content/en/guide/v10/hooks.md
- **Typo:** replaced `invoking` with `invoked`
- **Improvement:** removed "one" after "second" since there was no "one" after the word "first" in the same sentence
=> fix typo, improve wording

content/en/cli/getting-started.md
[It's been deprecated for over a year now](https://github.com/preactjs-templates/material/pull/30) and we don't want issues like https://github.com/preactjs-templates/material/issues/31 popping up if we can avoid them.
=> cli: Removing reference to material template

content/en/guide/v10/getting-started.md
Adds jsx-runtime aliases to the relevant configuration files on the Getting Started page.
Rollup and Snowpack are noticeably missing the `preact/test-utils` alias - is this intentional or should they also be added?
=> Add jsx-runtime aliases to Getting Started

content/en/guide/v10/getting-started.md
Nothing much to add, the current configuration cannot be copied/pasted without manually adding `export default` and it can bring confusion.
=> Fix Snowpack config for aliasing

content/en/about/libraries-addons.md
=> removed preact-boot

content/en/guide/v10/refs.md
=> Fix minor typo in reference guide

src/lib/content.js
Fixes three sets of cases:
1. Sections with `.`
* Example: "Arguments in `Component.render()`" on [Differences to React](https://preactjs.com/guide/v10/differences-to-react)
* The Issue: Link in ToC would be to `#arguments-in-component.render` when the element had an ID of `arguments-in-componentrender`
* Solution: Strip `.` from ToC links
2. Sections with `[` and `]`
* Example: "Getting `vnode.[property]` is deprecated" on [Debugging Preact Apps](https://preactjs.com/guide/v10/debugging)
* The issue: Link in ToC would be to `#getting-vnode.[property]-is-deprecated` when the element had an ID of `getting-vnodeproperty-is-deprecated` (also suffers from issue 1)
* Solution: Strip `[` and `]` from ToC links
2. Sections with `'`
* Example: "Don't access `this.setState` synchronously" on …
=> fix: Correcting table of contents link generation

src/style/markdown.less
The padding to ensure the header didn't overlap content headings was limited to h1-h3, which meant on pages with deeper nested sections, like [Getting Started's aliases](https://preactjs.com/guide/v10/getting-started/#aliasing-in-webpack), the content heading would be hidden behind the header.
Just need to ensure the padding applies to all headings, not just h1-h3 (although we only use up to h4)
=> fix: Corrects content padding to avoid header overlap

content/en/guide/v10/getting-started.md
I noticed this acronym, while clever, isn't the widely held definition for CLI. Per Wikipedia: https://en.wikipedia.org/wiki/Command-line_interface
=> Update acronym to match the more common definition

src/style/markdown.less
Since there is an `overflow: hidden` on many tags and classes such as `.markup`, overflowing things can get inaccessible on mobile pretty easily, and `overflow` needs to be manually set to `auto` in such cases.
Before the fix:
(it is impossible to read/copy the entire URL in that "Tip" blockquote.)
After the fix:
=> Fix blockquote overflow on mobile

content/en/guide/v10/preact-testing-library.md
Current example `expect(screen.textContent).toMatch("Current value: 6");`
failed with the following error message
expect(received).toMatch(expected)
Matcher error: received value must be a string
Received has value: undefined
queries like getByText should be used to work with Async APIs
like waitFor or findBy
=> Fix a bug in preact testing library usage example

content/en/tutorial/05-refs.md
Hey there,
Just noticed a couple typos while reading through https://preactjs.com/tutorial/05-refs (en) and figured it might be worth fixing.
Cheers.
=> Fixed typos in content/en/tutorial/05-refs.md

content/de/guide/v8/api-reference.md, content/en/guide/v10/api-reference.md
We've already removed the third parameter `replaceNode` to render in `v11`. Thought it'd be a good idea to hint at that in the current `v10` docs, so that users will avoid using it with `v10`.
=> Warn about `replaceNode` usage

content/en/tutorial/01-vdom.md, content/en/tutorial/03-components.md, content/en/tutorial/04-state.md, content/en/tutorial/05-refs.md, content/en/tutorial/06-context.md, content/en/tutorial/07-side-effects.md, content/en/tutorial/08-keys.md, content/en/tutorial/09-error-handling.md, content/en/tutorial/10-links.md, content/en/tutorial/index.md
Nice tutorial!
Chapters 5 and 7: I lowercased the comments for consistency.
Side notes (didn't do anything about these):
- The word "Component" is capitalized inconsistently. Just saying because it bothered me a bit (🙈).
- Semicolons are used inconsistently in the code blocks. (Noticed this only halfway through the tutorial so not a big deal. 😄)
- The underlining of the `<abbr>` in chapter 6 is almost invisible in dark mode (see the last word in the screenshot):
=> Fix typos in tutorial

src/style/index.less, src/style/markdown.less, src/style/variables.less
Bah, missed this in #835 and only after I said we don't need to extract this out to a variable as it's only used in one spot.
Ensures header doesn't overlap content headings
=> fix: Corrects padding to avoid header overlap

src/components/controllers/page/sidebar.module.less
Sorry, yet another post-banner adjustment.
Corrects the top of the sidebar being covered a bit, see image below:
=> fix: Ensures sidebar is not cut off due to banner

content/en/guide/v10/getting-started.md
When i was reading through the docs i was under the impression that i have to do the aliasing myself. 
It wasn't clear (nor is it clear from the preact CLI documentation) that this is done for you.
Maybe mentioning it in the CLI documentation as well wouldn't hurt.
=> Mention that preact cli handles alliasing

content/en/tutorial/01-vdom.md
'regardles' should read 'regardless' - fixed.
=> docs: Fix 'regardles' typo in tutorial

content/en/about/libraries-addons.md
I wrote a small helper that helps you run a Preact app/component on any website. It's useful for widgets on CMS website or E-commerce pages. There's ways of injecting props into your component from the outside page that are reactive and cause rerenders of your component.
=> Adds Preact island

content/en/guide/v10/getting-started.md, content/en/guide/v10/typescript.md
Re: https://github.com/preactjs/preact/issues/2748 & https://github.com/preactjs/preact/issues/3547, `"paths"` seemingly is becoming more and more required in order to solve type discrepancies between Preact and React.
Also duplicates the information from the 'Getting Started' page to the TS page, as the info was otherwise a bit fragmented which is less than ideal.
=> docs: Adds `paths` to recommendation for TS config

content/en/guide/v10/preact-testing-library.md
I assume this was left over from the previous API where `findByText` was destructured from the `render` return value.
=> fix: use `findByText` on `screen`

content/en/tutorial/09-error-handling.md
Thanks for the awesome tutorial.
I think the method here should be `getDerivedStateFromError`.
=> docs: Fix typo on the error handling tutorial page

content/de/guide/v8/progressive-web-apps.md, content/en/guide/v10/progressive-web-apps.md, content/en/guide/v8/progressive-web-apps.md, content/es/guide/v8/progressive-web-apps.md, content/fr/guide/v8/progressive-web-apps.md, content/ja/guide/v10/progressive-web-apps.md, content/pt-br/guide/v10/progressive-web-apps.md, content/pt-br/guide/v8/progressive-web-apps.md, content/tr/guide/v8/progressive-web-apps.md, content/zh/guide/v8/progressive-web-apps.md
Google no longer maintains developer page describing/defining PWAs (existing link 404s)
Found hyperlink in google docs here: https://developers.google.com/codelabs/pwa-in-play?hl=en#0
which now points to web.dev article for definition: https://web.dev/learn/pwa/
=> fix: Replace dead PWA link with working reference

src/components/controllers/page/index.js, src/components/controllers/page/style.module.less, src/style/markdown.less
Saw someone again linking to the v8 docs today and thought a slightly more aggressive banner is appropriate, especially with v11 coming up.
This simply makes the warning banner sticky and places it below the header while the user scrolls the page. Hopefully this should catch users following outdated links to where the warning might not be immediately visible, [like here](https://preactjs.com/guide/v8/differences-to-react/#whats-included).
=> refactor: Makes v8 warning banner sticky

src/template.html
=> Fix light scrollbar in dark mode

src/components/controllers/page/sidebar-nav.module.less
Wasn't able to add this as a comment to the other PR in time, was putzing around with colors.
I really, really like the changes! However, with the tighter spacing in the sidebar I feel like a hover effect would improve the experience a bit. I found it a bit harder to discern which link I was hovering over compared to the old style.
Certainly can tweak colors. This is just the brand @ 50% opacity.
=> refactor: Adds a hover effect to the sidebar nav

src/components/controllers/page/sidebar-nav.module.less
If one were to hover over category labels like "Introduction", "Essentials", "Debug & Test", etc. in the sidebar they'd get a pointer cursor despite these not being links or having any interactive mechanics. They're just plain labels, so default cursor is the correct state.
=> refactor: Disable pointer cursor for sidebar category labels

content/en/guide/v10/api-reference.md, content/en/guide/v10/components.md, content/en/guide/v10/context.md, content/en/guide/v10/forms.md, content/en/guide/v10/hooks.md, content/en/guide/v10/refs.md, content/en/guide/v10/tutorial.md, content/en/guide/v10/whats-new.md, content/en/tutorial/01-vdom.md, content/en/tutorial/02-events.md, content/en/tutorial/03-components.md, content/en/tutorial/04-state.md, content/en/tutorial/05-refs.md, content/en/tutorial/06-context.md, content/en/tutorial/07-side-effects.md, content/en/tutorial/08-keys.md, content/en/tutorial/09-error-handling.md, content/en/tutorial/10-links.md, src/components/code-block/index.js, src/components/controllers/repl/repl.worker.js, src/components/controllers/repl/runner.js, src/components/controllers/tutorial/index.js, src/components/controllers/tutorial/style.module.less
This PR changes the conditions on which we decide if we should add the `Run in REPL` link at the top right corner of a code snippet. Before this PR we'd always show it for every `js` or `jsx` code snippet, despite most of them being illustrative and not intended to be run. Basically, nearly all of our repl links were broken.
This PR changes that in that adding the repl link is an opt-in. It can be enabled by adding the `// --repl` comment in the first line.
```js
console.log("this code snippet WILL NOT have the 'Run in REPL' link");
```
vs
```js
// --repl
console.log("this code snippet WILL have the 'Run in REPL' link");
```
The `// --repl` comment is replaced by a new line when passed to the actual repl.
For most code snippets this is not enough though, since they require a little setup …
=> Opt-in into repl instead of always on

content/en/guide/v10/signals.md
Spotted by an eagle-eyed Twitter user: https://twitter.com/boris0crypto/status/1567231740015427586?s=20&t=HgVxE--d4uYMEwgkoqOwtA
Same thing was already corrected in `signals`'s readme: https://github.com/preactjs/signals/pull/69/files
=> fix: Correct signals example

content/en/about/project-goals.md
Reverts preactjs/preact-www#896
"thrash" was the correct word to use, not a spelling mistake. "Avoiding garbage collection trash" doesn't make much sense.
=> Revert "Update project-goals.md"

content/fr/about/we-are-using.md, content/pt-br/guide/v10/whats-new.md
The French version of "Companies using Preact" was missing a wrapper resulting in the following UI:
---
Additionally, as I was grepping for something, I happened to notice a translation in the the Brazilian Portuguese docs that stood out to me. While I admittedly don't speak a word of Portuguese, 'incrementar' is used numerous times throughout other translated pages (like in the [pt-br 'Hooks' page translation](https://github.com/preactjs/preact-www/blob/master/content/pt-br/guide/v10/hooks.md)), so I think it's pretty safe to call 'icrementar' a simple typo.
=> fix: Formatting issue in FR docs and typo in PT-BR

src/components/header/index.js
Silly mistake from a lazy copy/paste, sorry.
=> fix: Correct alt text on translation/i18n icon

content/en/tutorial/index.md
A very common piece of feeback is that the tutorial takes much longer than 10 minutes [[1](https://github.com/preactjs/preact-www/discussions/815)] and I've seen a few comments saying that the "in 10 minutes" gave them the wrong idea about the tutorial when starting it.
Some have spent nearly 10 minutes per page, others have skimmed and gotten through pretty quickly. so I've removed the time estimation altogether as I don't think we can really provide anything that's accurate for the wide audience that may go through it.
=> chore: Remove "in 10 minutes" portion of tutorial intro header

src/components/controllers/page/index.js, src/components/time/time.less
Kinda changed my mind on this. Originally, thought the 2 line version would look better. But looking at it again now I don't thing so anymore.
Before:
After:
=> Change blog post meta to fit in one line

content/en/blog/signal-boosting.md
This pull request fixes a couple of typos in the code examples that people spotted in Twitter:
* https://twitter.com/adamhaile/status/1574129208141529091
* https://twitter.com/runjep/status/1574298589094088705
=> Fix typos in signal-boosting.md

content/en/blog/introducing-signals.md
There's been at least [one case of someone confusing this example for two-way data binding](https://twitter.com/rauschma/status/1576235509306695680). If we're showcasing a new reactivity library, it's not a stretch for a user to think that an omitted input handler is an unnecessary one, especially if they're looking at the code samples alone (we do say this is a rendering optimization in the text above, but that can be missed). Hopefully adding an `onInput` should be a clear signal (pun somewhat intended) that we're not supporting two-way data binding with signals.
Alternatively, we could add a comment but I felt that might not catch users who are quickly skimming.
Will PR signal's docs with whatever direction we go with here, as we have a very similar example in one of the readmes.
=> docs: Clarify that signals + dom props != two-way data binding

content/en/guide/v10/differences-to-react.md, content/ja/guide/v10/differences-to-react.md, content/kr/guide/v10/differences-to-react.md, content/pt-br/guide/v10/differences-to-react.md
@rschristian 
https://github.com/preactjs/preact-www/issues/930
change link from [GlobalEventHandlers](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers) to [MDN's Event Reference](https://developer.mozilla.org/en-US/docs/Web/Events) on [differences to react](https://preactjs.com/guide/v10/differences-to-react) page
I've modified Japanese and English so far
=> modify dead link "GlobalEventHandlers" in Differences to React page

content/en/about/libraries-addons.md
I'm the maintainer of the library previously named `preact-signal-store`, but to support React I recently deprecated the library under that name so that I could create scoped packages like the main Signals repo.
This PR is just updating the reference to the deprecated repo to have the name of the new repo.
=> docs: update preact-signal-store to @deepsignal/preact in libraries-addons.md

src/lib/content.js
Closes #944
The [API Reference](https://preactjs.com/guide/v10/api-reference) page is better to test with as it contains functions  both w/ and w/out args in the table of contents.
=> fix: Table of Contents link gen w/ function args

src/components/header/style.module.less
It'll turn black if the user browses in light mode, which isn't right.
The `vertical-align` is unused; a leftover from when I was testing out various methods I suppose.
=> fix: Correct language picker dropdown arrow on light mode

src/components/sponsors/index.js
This PR updates the URL from the outdated link to Trivago's Open Source page to the currently working one.
The tried and tested demo is as shown:
https://user-images.githubusercontent.com/20269286/220933819-c08645e3-429b-42b9-9da8-83c849dba99d.mp4
=> url for trivago open source replaced with working url

src/components/header/style.module.less
the CSS is gross, partly because we don't render the search bar ourselves. but it seems to work decently, and now you can type more than one word into the input, haha.
This also addresses an issue where, since we added the `Blog` header nav link, the nav links were wrapping weirdly:
=> expandable search field on mobile

content/en/guide/v10/signals.md
I was reading the signals documentation and spotted what I believe to be a missing word. I believe the word missing is "use".
=> Typo: fix missing word on Signals page

content/en/guide/v10/getting-started.md, content/es/guide/v10/getting-started.md, content/ja/guide/v10/getting-started.md, content/pt-br/guide/v10/getting-started.md, content/zh/guide/v10/getting-started.md
Marvin mentioned this the other day in the slack and it's been something I've been thinking about for a while too, seeing as how we have a pinned issue warning against some Unpkg headaches in the main repo.
So long as grep isn't failing me, this should be the only remaining (non-code comment) reference: https://github.com/preactjs/preact-www/blob/500911ce4e2d0bbe988bb404bdbd492c3946defd/content/en/tutorial/index.md?plain=1#L22-L26
=> refactor: Replace unpkg with esm.sh in 'Getting Started'

content/en/tutorial/08-keys.md, package-lock.json, package.json, src/components/controllers/repl/repl.worker.js, src/components/controllers/repl/runner.js
It took some effort to get this working in the Tutorial in addition to just the REPL, but I'm fairly confident it's all functioning correctly now. 
The main benefit of this approach is that the REPL now supports importing any package.
[Here's an example](https://deploy-preview-971--preactjs.netlify.app/repl?code=aW1wb3J0IHsgcmVuZGVyIH0gZnJvbSAicHJlYWN0IjsKaW1wb3J0IHsgdXNlRWZmZWN0IH0gZnJvbSAicHJlYWN0L2hvb2tzIjsKaW1wb3J0IHsgdXNlQ29tcHV0ZWQsIHVzZVNpZ25hbCB9IGZyb20gIkBwcmVhY3Qvc2lnbmFscyI7CgpmdW5jdGlvbiBBcHAoKSB7CiAgY29uc3QgbnVtYmVyc1NpZ25hbCA9IHVzZVNpZ25hbChbMSwgMiwgM10pOwoKICB1c2VFZmZlY3QoKCkgPT4gewogICAgc2V0VGltZW91dCgoKSA9PiB7CiAgICAgIG51bWJlcnNTaWduYWwudmFsdWUgPSBudWxsOwogICAgfSwgMTAwMCk7CiAgfSwgW10pOwoKICByZXR1cm4gbnVtYmVyc1NpZ25hbC52YWx1ZSA%2FICgKICAgIDxOdW1iZXJzIG51bWJlcnNTaWduYWw9e251 …
=> Switch REPL + Tutorial runner to Rollup + ESM.sh

src/prerender.js
Fix for now, though CLI should handle this better. An uncaught error should not result in a `Failed to load` warning that continues on.
=> fix: Ensure GH API error doesn't break prerendering

content/en/about/libraries-addons.md
Good morning.
I've did a tiny update via the github UI to update the link to current material UI example
=> Chore: Update libraries-addons.md with the updated material-ui link

src/components/controllers/tutorial/style.module.less
Might be opinion, but I think it's a bit easier to read without the horizontal scroll if we can help it.
=> fix: Mobile content width on tutorial

content/en/guide/v10/signals.md
#992
We may need to include `useSignalEffect()` in the "Local state with signals" section. However, since `effect()` hasn't been introduced in that section yet, I've only added it to the API list for now.
=> Add `useSignalEffect` to the API list

content/en/guide/v10/refs.md, content/ja/guide/v10/refs.md, content/pt-br/guide/v10/refs.md, content/zh/guide/v10/refs.md
Looks pretty weird in the pages `toc`/Table of Contents:
=> fix: weird look

content/en/about/libraries-addons.md
I have developed a form library for Preact with signals. The library is well documented at: https://modularforms.dev/
=> Add Modular Forms to Libraries & Add-ons

content/en/guide/v10/context.md
[Someone on Slack](https://preact.slack.com/archives/C3NMBSJKH/p1686255895690249) was confused about why `createContext` needs an initial arg when they've already set the value with a `Provider`, so I think it'd be good to add a little note here.
Reworded [React's description](https://legacy.reactjs.org/docs/context.html#reactcreatecontext) slightly; first sentence is verbatim, not sure if that's problematic. Open to suggestions.
=> docs: Add note about initialValue arg in `createContext`

src/components/header/index.js, src/components/header/style.module.less
When header items with dropdown menus were opened, the drop down arrow would stay white, resulting in it disappearing:
=> fix: Minor styling issues in header

src/components/controllers/repl/repl.worker.js
fixes #1008
It looks like esm.sh now has a new import when the file from https://esm.sh/preact@10.17.1 is initially loaded 😅 this amounted to us throwing an invalid URL for the block that is shielded with `try catch` in doing so it works correctly.
Example output of id, importer
```
/stable/preact@10.17.1/es2022/preact.mjs preact
/stable/preact@10.17.1/es2022/preact.mjs preact/hooks
/stable/preact@10.17.1/es2022/hooks.js preact/hooks
/stable/preact@10.17.1/es2022/preact.mjs stable/preact@10.17.1/es2022/hooks.js
```
all of these start with a slash but aren't valid URLs when combined.
=> support cascading import

content/en/guide/v10/components.md, content/en/guide/v10/hooks.md, content/en/guide/v10/whats-new.md
Inspired by https://x.com/windchime_yk/status/1707583523052453934?s=20
Mostly just to make error boundary info more discoverable, whether you're coming from a search engine or just searching our own docs, as we never actually use "error boundary" despite that being the prevailing term.
=> refactor: Document error boundaries specifically

package-lock.json, preact.config.js, src/components/controllers/repl/examples/todo-list-signal.txt, src/components/controllers/repl/repl.worker.js
Signals REPL example was failing cuz we were loading two copies of Preact on the page. The repl file imported 'preact' which esm.sh resolved to `esm.sh/preact@10.18.0`. The repl file also imported `@preact/signals` which also imports `preact` but esm.sh puts the version from the signals package.json on that import so the signals package imported `preact@10.17.0`.
This PR fixes the REPL by forcing all esm.sh URLs to have the `external=*` query param meaning any external imports are imported using bare specifiers (e.g. `preact` instead of `preact@10.17.0`). This ensures any imports transitive imports from esm.sh go through our bundler to get resolved, and we can resolve them to the same URL.
I've also updated the rollup config to use `resolveId` to resolve bare module specifiers to esm.sh …
=> Fix signals REPL example

content/it/blog/introducing-signals.md
This was the cause of the failure to deploy. `yaml` would choke upon attempting to parse it
=> fix: Invalid yaml structure in Italian translation of signals blog post

content/en/guide/v10/getting-started.md
Closes #1019
Sorry for this diff being a bit messy, can split it up.
Biggest changes:
- The TS section was moved under 'Aliasing React to Preact' and I really disliked the wording so I rewrote it (I wrote that text, to be clear -- this is self-criticism). The existing note on `skipLibCheck` was also pretty wrong (again, my bad) so I expounded a bit as I know some people have mentioned it in the Slack.
- Added a section on `<script type="importmap">` as we're fielding quite a few issues about it these days. Hopefully this will help get some people on the right track (verbiage feedback appreciated!)
=> docs: Refine 'Getting Started' text, add ImportMap examples & docs

.github/workflows/ci.yml, preact.config.js
Also catch yaml parsing errors -- the actual error messages I've found to be pretty junk, so they're not surfaced. For instance, the issue in #1028 results in the following:
> All collection items must start at the same column
Frankly it's easier to scan the frontmatter for issue than it is to try to figure out what in the world that means
=> CI: Add build pipeline

src/components/code-editor/style.module.less, src/components/controllers/tutorial/style.module.less
This adds `scrollbar-color` styles so that the look and feel of scrollbars on Firefox matches Chrome and Safari.
This property is supported in Firefox and soon to be Chrome and overrides the `::-webkit-scrollbar` styles in Chrome.
=> chore: Add scrollbar-color to styles

src/style/markdown.css
From #1012, fixes #1041
Moves entire block into `content-region[name*='guide']` so the styles don't leak out
=> fix: Fragment links incorrectly hiding blog titles

content/en/guide/v10/signals.md
The current documentation did not mention the possibility of specifying clean up functions for effects at all, which might be confusing since such possibility is only obvious from reading the source code.
These remarks were added in the effects section, together with a code example, and its corresponding API section.
=> Add documentation for clean up functions in effects

src/components/controllers/page/style.module.css, src/components/footer/style.module.css
I have a taller browser than most (1440p), but this can also be seen on mobile on a few pages.
Before            |  After
=> fix: Make footer sticky

content/en/blog.md, content/ru/blog.md, content/zh/blog.md, src/components/controllers/page/index.js, src/components/controllers/repl/index.js, src/components/controllers/tutorial/index.js, src/components/controllers/utils.js, src/lib/page-title.js, src/prerender.js
This addresses a few things:
- REPL doesn't set the page (browser) title
- This can be seen most easily by opening [this link](https://preactjs.com/guide/v10/getting-started) to the 'Getting Started' page and then switching to the REPL from the header -- the browser title will still be 'Getting Started ...'
- The prerendered titles do not match the titles as they'd be set client-side
- I like the prerendered titles way more, `Getting Started - Preact Guide` vs `Getting Started | Preact: Fast 3kb React alternative with the same ES6 API. Components & Virtual DOM.` See below, I think this might've been a bug.
- Upon extracting out the title creation, I also tried to make `/page` less of a grab-bag and moved most of the main utilities out. It's still not ideal and can use some refactoring …
=> fix: Browser page titles

content/de/index.md, content/en/index.md, content/es/index.md, content/fr/index.md, content/it/index.md, content/ja/index.md, content/kr/index.md, content/pt-br/index.md, content/ru/index.md, content/tr/index.md, content/zh/index.md, src/style/home.css, src/style/index.css
Whether or not multiple `<h1>` are "valid" is quite murky at the moment, as while the WHATWG HTML spec says it's a-ok if they're in `<section>`s, reality is that a lot of browsers and accessibility tools don't quite follow or acknowledge the nesting "as they should" (with some arguments being that the spec is problematic and should not be followed). This has been the case for well over a decade now and is mostly in a stand-still from my understanding.
It's easy enough for us to "correct" anyhow, a single `<h1>` for the entire page followed by `<h2>` for the rest conveys the meaning we need.
=> refactor: Ensure landing page only has a single `<h1>`

content/en/guide/v10/typescript.md, content/ru/guide/v10/typescript.md
These days the TypeScript recommends to use the `interface` keyword instead of `type` in their docs:
https://www.typescriptlang.org/docs/handbook/typescript-in-5-minutes.html
> You’ll see that there are two syntaxes for building types: Interfaces and Types. You should prefer interface. Use type when you need specific features.
For typing component props whether you use `type` or `interface` hardly matters, since the differences mainly show up when you combine or extend types which is rare with props. That said it's better for us to align with the TS docs.
=> docs: TS switch from `type` to `interfaces`

content/en/guide/v10/components.md
Updated the parameters to match what's passed in by the code.
I went with just "context" rather than "nextContext", as it's shorter and still unambiguous.
Also wondering whether it would be helpful to specify the expected return value for `getDerivedStateFromProps`. Being new to Preact/React, I didn't know that it should return an object with the updated state.
=> Update lifecycle method parameters

content/de/index.md, content/en/index.md, content/es/index.md, content/fr/index.md, content/it/index.md, content/ja/index.md, content/kr/index.md, content/pt-br/index.md, content/ru/index.md, content/tr/index.md, content/zh/index.md, src/components/code-block/index.jsx, src/style/home.css
`marked` is, unfortunately, turning this:
```html
<div>
<pre repl="false"><code class="lang-jsx">
import TodoList from './todo-list';
render(&lt;TodoList /&gt;, document.body);
</code></pre>
</div>
```
into this:
```html
<div>
<pre repl="false"><code class="lang-jsx">
import TodoList from './todo-list';
<p>render(&lt;TodoList /&gt;, document.body);
</code></pre></p>
</div>
```
Which breaks the code blocks pretty badly, cutting off everything after the first blank line. This is due to the fact that blank lines are an exit condition in Markdown, so the second line on out is then a paragraph.
To fix this, I've swapped out the blank lines with a `<br>`, and then in our `CodeBlock` component, made sure it could handle multiple children (as it normally just grabbed the first).
This should only …
=> fix: Home examples

src/components/sponsors/index.jsx
[Google recommends `rel="sponsored"`](https://developers.google.com/search/docs/crawling-indexing/qualify-outbound-links), but that seems to be non-standard. `rel="nofollow"` was the previous recommendation, so I added that in too.
=> refactor: Add `nofollow` & `sponsored` to sponsor links

src/components/we-are-using/style.module.css
From Slack: https://preact.slack.com/archives/C3NMBSJKH/p1710520457800869?thread_ts=1710518686.332509&cid=C3NMBSJKH
`name` was exact so `/about/we-are-using/` didn't match :facepalm:
The reproduction is that going to the site and then navigating via the menu would land the user on `/about/we-are-using`, but if you refreshed, that'd become `/about/we-are-using/`
=> fix: Ensure text is centered on 'we are using' page

src/components/controllers/repl/index.jsx
Closes #1079, upon clicking any 'Run in REPL' button, the REPL would open, but the code snippet would not be carried over. User would instead see a default or what they had open previously.
Missed in the iso migration, query params aren't passed as bare props (as they are in `preact-router`).
=> fix: 'Run in REPL' button

src/style/markdown.css
Credit to @lukewarlow 
The problem with the current implementation is that you get these big gutters upon scrolling back up in the page:
=> chore: Use correct CSS property for avoiding header overlap on scroll

src/components/controllers/blog-page.jsx, src/components/controllers/doc-page.jsx, src/components/controllers/markdown-region.jsx, src/components/controllers/tutorial-page.jsx, src/components/edit-button/index.jsx, src/components/sidebar/sidebar-nav.jsx, src/lib/i18n.jsx, src/lib/localstorage.js, src/lib/use-resource.js
Mostly missed in #1073, though also last night in #1100
Should use `path` in most of these cases, I blanked and didn't realize `useLocation` offers that which solves a few of our issues.
=> fix: Ensure language query params work again

src/style/variables.css
Bah, went to close my editor and it asked if I really wanted to throw away this change. Was meant to be in #1053, it (correctly) lives [here now](https://github.com/preactjs/preact-www/blob/72353ed91c6e6ea157965ef733a1a695e04213fa/src/style/docsearch.css#L1)
It looks to be correctly dedupded, there's no stylesheet bloat, but I don't trust that will always be the case.
=> chore: Remove duplicate docsearch CSS import

CONTRIBUTING.md, README.md
Follow-up to #1102, moves all general repo information to `Contributing.md`. I realized past Ryan was wrong and splitting general architecture & contributing info in two separate docs was a bad call.
Mimicking some other projects, the ReadMe now contains a more obvious link to our Slack & encouragement for opening issues on spotting a bug or confusing language and whatnot.
Of course, verbiage suggestions welcome if anything seems like it could be better.
=> chore: Move all repo information to Contributing

src/assets/_redirects, src/components/content-region/index.jsx, src/components/controllers/markdown-region.jsx, src/components/controllers/style.module.css, src/types.d.ts
Fixes two hydration issues on the 404/not found page:
- The Preact logo/home nav in the header is missing 
- The content overlaps the 'Edit this Page' link, making it unclickable
=> fix: Ensure Netlify routes to `/404` when it cannot find static HTML for a page

content/en/guide/v10/preact-testing-library.md, content/en/guide/v10/web-components.md
I noticed a couple of typos while working through the docs, so here's a PR to fix them up.
https://preactjs.com/guide/v10/preact-testing-library#using-content
https://preactjs.com/guide/v10/web-components#passing-slots-as-props
=> chore: fix typos in testing library and web components pages

content/en/guide/v10/components.md
I previously added this image, but it seems it's broken, maybe because assets no longer are (or never were?) contained in a `/assets` directory. Removing `/assets` from the image `src` should fix this.
=> fix: broken image on Components page

src/components/controllers/tutorial/style.module.css, src/components/header/style.module.css
Closes #847
First two are from this PR preview, last is from the linked issue:
With hidden toolbar |  Without | Previous State
:-------------------------:|:-------------------------:|:-------------------------:
Not sure if all mobile browsers can hide their toolsbars (that's Safari from me), but we've at least reclaimed a good portion of screen real estate. Maybe we could do some sort of expanding/collapsing header too (or in place of this), but that'd need some more thought & work.
Hopefully this isn't problematic, it's only hiding the banner in a pretty specific situation when vertical height is pretty badly needed.
=> refactor: Hide banner on short viewports (like rotated phones)

src/components/sponsors/style.module.css
Broke in #1124
Vite mangles this in their build process (dev works fine), creating a different (and incorrect) selector. Dunno what that's about but removing a bit of nesting will fix it anyhow.
=> fix: Color inversion of sponsors on hover/focus

content/en/guide/v10/hooks.md
Currently the comment reads `// Display a nice error message`, which doesn't make sense, seems to be copied from the `useErrorBoundary` example?
=> Fix `useId` example comment

src/components/controllers/tutorial-page.jsx, src/components/controllers/tutorial/index.jsx, src/components/routes.jsx
Admittedly this is a bit of a hack, but the tutorial pages have their own loading state which isn't quite correct anymore and is therefore creating a bit of jank when you switch between the steps (`/01-vdom` -> `/02-events`). This solution probably isn't perfect but it improves the situation quite a bit (from my testing, lmk if anyone sees anything different) for the time being until I get to properly refactor it.
I didn't touch the tutorial much during the preact-cli/preact-router -> vite/preact-iso refactor, probably just needs a bit of a touch up to align with the other pages but that'll take some time. For now, this drilling seems to help.
=> fix: Match tutorial loading state to Router

src/components/controllers/repl/style.module.css, src/components/controllers/style.module.css, src/components/sidebar/style.module.css, src/style/docsearch.css, src/style/index.css, src/style/markdown.css
Missed in #1131
The Ukraine banner hides with short displays ports (such as a phone turned sideways) but the extra height was only accounted for on the tutorial, where this was requested. I guess I forgot to grep through and add queries elsewhere, yikes.
=> fix: Ensure consistent padding on mobile in header

src/components/splitter/index.jsx
The only place we use this is on the tutorial intro/index page, where it's pretty bad. The content quite obviously shifts from 50% width to 100%, jumping from the left side of the screen to then be centered.
=> refactor: Fix splitter pop-in for forced sizes

package-lock.json, package.json, plugins/html-routing-middleware.js, src/components/code-editor/index.jsx, src/components/controllers/repl-page.jsx, src/components/controllers/repl/examples.js, src/components/controllers/repl/index.jsx, src/components/controllers/repl/runner.jsx, src/components/controllers/tutorial/index.jsx
(and hopefully simplifies the component considerably)
The only intentional difference to the previous system is that the 'Share' button will now prefer the `?example` query if applicable -- previously it would always swap that to `?code=...`.
Should be a couple fewer renders and a clearer flow. Working on #1148 and was a tad overwhelmed with how state was bouncing around.
=> refactor: Better utilize suspense in REPL

src/components/controllers/tutorial/index.jsx
From #1150, was left in a stash :/
Tutorial errors are swallowed & not displayed to the user because of this.
=> fix: Ensure tutorial errors are displayed

plugins/precompile-markdown/index.js, src/components/controllers/repl/error-overlay.jsx, src/components/controllers/repl/errors.js, src/components/controllers/tutorial-page.jsx, src/components/controllers/tutorial/index.jsx, src/components/controllers/tutorial/style.module.css, src/components/routes.jsx, src/lib/prerender-data.jsx, vite.config.js
This should be the last of the vite & preact-iso migration changes, sorry it took so long for me to land.
Better utilizes suspense, so now we can just rely on the router loading state -- no longer is there any loading of the REPL/Code Editor separately post-mount. This also fixes the full unmount of the route when navigating between tutorial steps, structure is now preserved & content is simply swapped out. Feels a lot smoother.
Certainly let me know if any issues are spotted -- I spent a fair bit of time going through different situations manually but this is the most complex page we have by a fair margin, which is why it was left for last.
=> refactor: Better utilize suspense in Tutorial

package.json, src/components/controllers/repl-page.jsx, src/components/controllers/repl/examples.js, src/components/controllers/repl/index.jsx, src/components/controllers/tutorial/index.jsx
Few things I ran into in #1148 that can be extracted a bit.
=> refactor: Clean up a bit post #1155 & #1150

src/components/controllers/repl/index.jsx, src/components/controllers/repl/runner.jsx, src/components/controllers/tutorial/index.jsx
Closes #1159
Instead of debouncing the REPL runner by 500ms across the board, limit it to user interaction. This lets us switch examples in the REPL or pages in the tutorial faster -- the former is especially relevant, as dynamically pulling modules from `esm.sh` means there often will be a delay anyhow. Decreasing the baseline delay is therefore quite useful to make the editor seem faster & more fluid.
=> refactor: Only debounce REPL runner on user input

src/components/controllers/repl-page.jsx, src/components/controllers/repl/index.jsx, src/components/controllers/repl/query-encode.js
The `Todo List (Signals)` example has a couple of emojis which `atob` and `btoa` will of course trip on.
=> fix: Support unicode in REPL query param

src/components/controllers/repl/runner.jsx
Fixes #1161 
The information on this is a bit lacking, but it seems FireFox asynchronously creates the iframe doc once appended into the parent whereas Chrome and Safari do it synchronously, then, upon loading, FireFox will replace the inserted document if it's already been altered? Not 100% on that, but this seems to do the trick.
=> fix: REPL style insert in FireFox

content/en/guide/v10/forms.md
re: post in slack, people might find this example confusing so we should probably just cut it. I moved some sentences around a bit, I think it's more clear? Not sure, let me know!
=> docs: Update controlled component example

src/components/controllers/repl/index.jsx
Our `useStoredValue` hook defaults to preferring localStorage which we do not want as [we already have a defined list of fallback values](https://github.com/preactjs/preact-www/blob/77476f289ed406580761a03187bc538178812414/src/components/controllers/repl-page.jsx#L34-L39), namely, with query params (`?code` or `?example`) taking precedence.
As such, this bug breaks an attempt to load a code sample from a link if the user has previously used our REPL.
=> fix: Ensure passed-in initial code overrides localStorage in REPL

src/components/controllers/tutorial/index.jsx
re: https://x.com/danvitoriano/status/1815851188643926179
Missed in the CodeMirror 6 migration -- we're essentially now using a `slug` prop to determine when CodeMirror needs to swap out the code content vs letting its internal state continue to handle changes. As such, this PR adds a `?solved` redirect to address this.
Keep in mind that `solutionCtx.solved` can have additional requirements, like having the user click a button to test their new event handler, so we can't reuse it.
=> fix: Ensure the 'Solve' button in the tutorial works

content/en/guide/v10/getting-started.md
Closes #1172
Reasonable thing to add, IMO, especially next to tools that have it baked-in at all times.
=> docs: Explicitly note preset-vite in alias prelude

content/en/blog/prerendering-preset-vite.md, src/config.json, src/lib/prism.js, src/style/prism.css, src/style/variables.css
Not much of a writer so let me know if there are any opinions on topics, direction, etc.!
=> blog: Prerendering with `@preact/preset-vite`

content/en/about/libraries-addons.md, content/kr/about/libraries-addons.md, content/ru/about/libraries-addons.md
Looks like this folder was renamed to add "UI" at some point, I've updated the URL accordingly
=> Update URL for Material UI Preact

content/en/guide/v10/no-build-workflows.md
Just a typo fix for the documentation.
=> docs: Fix typo in no-build-workflows.md

src/components/controllers/repl-page.jsx, src/components/controllers/repl/runner.jsx
I've been linking to a few REPL examples over the past few days, and one thing that's slightly bothering me is that we show the confirmation/warning for running untrusted code _before_ showing the code itself. The user has to gauge whether they trust whoever provided the link rather than if they trust the code (or copy the query into a base64 decoder and read that, I suppose).
This isn't perfect (see the `TODO:` I left behind), but it moves the confirmation check further ahead into the REPL runner itself. This lets the user (partially) see the code populated in the editor pane before they're forced to accept or refuse.
=> refactor: Move REPL query safety check into runner

content/en/blog/simplifying-islands-arch.md, src/config.json
Draft write up for islands arch
=> docs: add blog post for diy islands

content/en/about/demos-examples.md, content/kr/about/demos-examples.md, content/ru/about/demos-examples.md, content/zh/about/demos-examples.md
Fixing webmakerapp malware link in content=>demos&examples
=> issue#1188 fixing malware link in demos & examples

content/en/guide/v10/switching-to-preact.md
@JoviDeCroock let me know what you think of this. I went with a generic link to our tracker w/ a "suspense" query, rather than any particular issue, as this probably isn't likely to stay in sync with our tracker? Can drop a specific mention of the hydration issue if you think we need it though.
=> docs: Soften language around suspense

src/components/blog-overview/index.jsx, src/components/content-region/index.jsx, src/components/controllers/blog-page.jsx, src/components/controllers/doc-page.jsx, src/components/controllers/not-found.jsx, src/components/controllers/repl-page.jsx, src/components/controllers/tutorial-page.jsx, src/components/header/index.jsx, src/components/sidebar/sidebar-nav.jsx, src/lib/use-content.js, src/lib/use-resource.js
Simple prefetching for content in a few cases:
- header links
- sidebar links
- links within markdown content
- blog overview links
Makes for a bit snappier nav on desktop.
=> feat: Basic content prefetch

content/en/guide/v10/switching-to-preact.md
This PR fixes a lil typos on switching-to-preact.md.
=> docs: Fix typos and enhance readability on switching-to-preact.md

index.html
This was a relic from when docsearch was loaded via CDN which hasn't been the case for a fairly long while now. Switching it over to esm.sh, however, could be useful for our REPL.
=> chore: Switch CDN preconnect over to esm.sh

src/components/footer/style.module.css, src/style/markdown.css, src/style/variables.css
Can see this from local lighthouse runs or [pagespeed insights](https://pagespeed.web.dev/analysis/https-preactjs-com/7ipoxsksca?form_factor=mobile).
While the message seems to suggest a contrast issue, this isn't actually the case -- our contrast ratios are 6.53:1 & 6.01:1 w/ light & dark preferences respectively, both hitting the WCAG AA standards. In fact, changing this to #fff on #000 still does nothing to dismiss the message. The actual issue, which I found unclear at least, is that links aren't meant to rely on color alone and so we need text decoration here. Reasonable enough.
=> refactor: Fix lighthouse accessibility issue in footer links

plugins/precompile-markdown/index.js, plugins/precompile-markdown/prism.js
It's our only missing highlight language, and now that Prism is server-only, I figure it's worth adding now (as it's a bit chonky).
The "Getting Started" & "Unit Testing with Enzyme" pages have a few examples to look at.
=> refactor: Add bash syntax highlighting

src/components/code-editor/style.module.css, src/components/controllers/tutorial/style.module.css, src/components/header/style.module.css
Not an active issue at the moment to my knowledge (Chrome, FF, and Safari all appear to work fine), but was playing around with `lightningcss` (it's worse for us right now, seems to always expand `:is()` despite our targets) and learned that `@keyframes` is not allowed to be nested per the spec.
Un-nesting them makes more sense (they're global-ish names, after all, what would nesting do?) and gets us back to adhering to the spec so I figure it's a change for the better.
=> refactor: Un-nest CSS keyframes

content/en/guide/v10/hooks.md, content/en/guide/v10/refs.md, src/components/tab-group/index.jsx, src/components/tab-group/style.module.css, src/components/widgets.js
I've found the refs doc rather lacking for a while, hope this is an improvement. Notably, it adds hooks examples, mentions values other than DOM nodes, and mentions the new cleanup functions added in 10.23.
Should address #1001 too, I expanded the warning for the callback refs section to (hopefully) clarify that a bit better.
Edit: Will try to do something similar to the Context doc, either during more gaps in holiday celebrations or in the next couple of weeks.
=> refactor: Rewrite Refs doc

content/en/guide/v10/context.md
Follow up to the Ref doc, tries to bring some updates here too.
Adds mention of the core problem Context attempts to solve (prop drilling), takes users step-by-step in setting up their context, shows how to update it/tie to to state, adds a `useContext` example, and switches the examples to use hex colors instead of theme strings -- whilst using the "theme" class is a good demo in theory as it's pretty real-world, we don't have any CSS inserted into the demos (and doing so would inflate the REPL code a bit, making it less focused) so there is no visual cue whatsoever. Hex codes therefore felt better.
=> refactor: Rewrite Context doc

content/en/guide/v10/differences-to-react.md
Sorta addresses #924 (though I think we'll need a proper change to the way we convey compat, as Marvin mentions -- that's a bigger messaging issue though).
=> refactor: Mention parts of React 18.x & 19.x are supported

content/en/guide/v10/context.md, plugins/precompile-markdown/index.js
Tracked down the issue w/ that load-bearing comment: that trailing `\n+` gobbles up all blank lines, not allowing the subsequent title to be detected (as we're not using the multiline flag). `marked` also removes extraneous newlines (as it should, IMO) so just inserting extra blank lines wouldn't help (it'd be super fiddly & error prone to rely on anyhow).
This can also be seen on the Hooks page, `useId` doesn't show up in the ToC at all.
=> fix: Table of Contents with subsequent headers

src/config.json
Not quite sure what has been going on here but we've not been getting updated search entries for 2+ years now (so no mention of signals, for example, will come up).
They key was always the same, only changing appId last year as we bumped versions... still not quite sure how we could have working results, but outdated, as it was pointing at the correct application. Swapping in my (newly granted) key & appId seems to get search back on track though which I'm pretty pleased to see working again.
=> fix: docsearch

content/en/guide/v10/forms.md, src/components/controllers/repl/examples/style.css
Follow up to the refs & context rewrites, trying to add clarity here too.
Of note:
- Adds hooks examples
- Shows forms via `FormData`
- Adds a suggestion to not rely on component state for all inputs
- Tries to expound the Controlled Component issue
=> refactor: Rewrite Forms doc

content/fr/guide/v8/differences-to-react.md, content/fr/guide/v8/extending-component.md, content/fr/guide/v8/forms.md, content/fr/guide/v8/getting-started.md, content/fr/guide/v8/linked-state.md, content/fr/guide/v8/progressive-web-apps.md, content/fr/guide/v8/switching-to-preact.md, content/fr/guide/v8/unit-testing-with-enzyme.md, content/fr/index.md
This PR fixes a few typos I spotted in the French translation.
=> Fix typos in French translation

content/zh/guide/v10/signals.md
Fixed a typo: changed '称为' to '成为'.
Note: “称为” means “to be called or named,” while “成为” means “to become a part of something.”
=> fix: typo in zh signals.md

package-lock.json, package.json, src/components/blog-overview/index.jsx, src/components/content-region/index.jsx, src/components/controllers/repl-page.jsx, src/components/controllers/repl/index.jsx, src/components/controllers/tutorial-page.jsx, src/components/controllers/tutorial/index.jsx, src/components/header/index.jsx, src/components/header/style.module.css, src/components/routes.jsx, src/components/sidebar/sidebar-nav.jsx, src/lib/use-content.js, src/lib/use-repl.js, src/lib/use-resource.js
Using the recent addition of the `.preload()` method from `preact-iso@2.8.0`, this PR preloads our few split chunks on mouse over and also preloads the REPL Code Editor & Runner chunks. Depending on how quick you are at clicking, can be a pretty considerable speed up.
Also refactors `use-resource` & `use-content` a bit, adding a new `use-repl` as well. Should be a bit easier to follow now.
=> feat: Preload routes and repl

content/en/guide/v10/hooks.md
Since Jason added me to the Algolia instance a few weeks ago I've been getting weekly "round-up" summaries on the searches our site receives and for the past 4 weeks straight we've had a handful of failed searches for `useImperativeHandle`.
As such, I added an entry & tiny example for `useImperativeHandle`, creating a new section in our hooks docs to house both it and `useRef` as it seems to me like they should be grouped together.
=> docs: Add info on `useImperativeHandle`

content/en/guide/v10/differences-to-react.md
Another search term we're getting a lot of misses on is `className`. Algolia excludes code blocks from its indexing (which is very reasonable) and it turns out codeblocks are the only place we use this.
Adding an explicit mention of it here makes the most sense to me, I would guess that users are trying to check that `class` is the exact same as `className` in their components.
=> docs: Add explicit mention of `className` in content for Algolia

content/en/guide/v10/typescript.md
Something that's popped up a few times in the last few days, we should generally point users to `.currentTarget` now that our types will infer the correct element automatically when possible. Impossible to avoid casting with `.target` which is a bit cumbersome.
Not sure if we should explicitly state why `.currentTarget` should be preferred over `.target`, or at least, I'm not sure how to phrase that beyond "React does weird things with their events".
=> docs: Switch TS Events docs to use `.currentTarget`

src/lib/use-resource.js
Bit silly, not quite sure how I let this happen.
As `useResource` didn't force a rerender upon resolving promises, we were relying on a (perhaps problematic) double render in `preact-iso`, fixed in https://github.com/preactjs/preact-iso/pull/72. Without this fix, content fetches won't trigger a rerender and so all pages will be empty, minus the header as it exists outside the router.
=> fix: Correct 'useResource' suspense impl

content/es/guide/v10/getting-started.md
It looks like it was translated by a translator because instead of keeping React, it was translated into "reaccionar" (reaction)
=> fix: Correct translation for "React" in Spanish

src/components/sidebar/style.module.css
I noticed on mobile our sidebar goes off the screen a bit, making it a bit difficult to tap on the bottom few options. We have padding that's meant to accommodate for this but also a faulty `height` value set which causes issues. Easy fix though.
Both of these screenshots are scrolled as far down as possible, hence the issue:
=> fix: Sidebar going off screen on mobile

content/en/guide/v10/debugging.md
Closes #1239
Would love suggestions if anyone has some, I'm not sure this is as clear as it could be. I struggled a bit as this is a rather unique situation in which browsers have actually spec'd how to handle incorrect tables for so long that MDN was actually documenting the _incorrect_ table structure in most of their examples for years, as it could be safely relied upon (thankfully that's changed a bit more recently).
=> docs: Expound upon 'Improper nesting of table' warning

content/en/guide/v10/no-build-workflows.md
It worked as it was, but this addresses two things:
1. Bit silly to use JSX within the render call for a `htm` example (oops)
2. Some users get a bit stuck with how to refer to components using `htm`, and whilst the example does show using components already (`<${Button}>`), I figure an additional sample is good as it can be easy to miss in the component return. As such, I removed the `// --repl-after` comment so that it shows up in the code block on the docs page.
=> docs: Fix HTM example in 'No build workflows'

content/zh/guide/v10/switching-to-preact.md
Chinese translation of the following sections of the Preact documentation：
+ Guide(v10) / Switching to Preact
=> docs: Wrote missing translations into Chinese of Preact documentation

src/components/footer/style.module.css, src/style/markdown.css
When tabbing through a doc page, the anchor icons stay hidden as their opacity is only triggered on hover for the header. We should also increase the opacity on focus.
Also cleans up a couple tiny other issues I noticed
=> fix: Anchor transparency when tabbing

package-lock.json, package.json
Upon loading the REPL in Firefox with sourcemaps enabled in their devtools, users will be met with the following warnings:
```
Source map error: request failed with status 404
Resource URL: https://preactjs.com/assets/repl.worker-BMYdljCC.js
Source Map URL: repl.worker-BMYdljCC.js.map
```
```
Source map error: Error: URL constructor:  is not a valid URL.
Stack in the worker:resolveSourceMapURL@resource://devtools/client/shared/source-map-loader/utils/fetchSourceMap.js:56:22
getOriginalURLs@resource://devtools/client/shared/source-map-loader/source-map.js:73:24
workerHandler/</<@resource://devtools/client/shared/worker-utils.js:115:52
workerHandler/<@resource://devtools/client/shared/worker-utils.js:113:13
Resource URL: null
Source Map URL: null
```
Second one is sorta nonsense, and I …
=> fix: Bump preset-vite to dismiss repl sourcemap warning

src/lib/prerender-data.jsx
Missed in #1260, sorry
`vite-prerender-plugin` uses a more generic ID as it's not necessarily tied to Preact. Data was still getting injected, but not found correctly, leading to a flash of the version number in the header
=> fix: Prerender data

src/lib/i18n.jsx
Was using the default/previous render's `lang` instead of the newly derived value to set on the document element.
As such, `/?lang=es` (for example) wouldn't update the `lang` attribute on the root `<html>`
=> fix: Initializing user language

src/components/controllers/blog-page.jsx, src/components/controllers/guide-page.jsx, src/components/controllers/page.jsx, src/components/controllers/repl-page.jsx, src/components/controllers/tutorial-page.jsx, src/components/routes.jsx
Makes three changes:
- Wraps all routes w/ suspense data fetching in `<ErrorBoundary>`
- Shouldn't really be an issue either way, the intermediaries are quite thin so rerendering them shouldn't be a problem, but a healthy sprinkle of boundaries cuts down on renders all the same
- Extracts common/generic pages from doc/guide pages
- Generic pages like `/`, `/about/*`, `/blog`, etc. flowed through `DocPage`, leading to it having to distinguish guide from non-guide pages for the sidebar and the couple of doc warnings we have. Better to extract that out, easier to follow & understand.
- Extracts the 'Generic Routes' from being formed in-line in the `<Router>`
- Completely static, no reason to ever recalculate that
=> refactor: Wrap suspending pages w/ error boundaries, extract generic pages from doc pages

src/components/content-region/index.jsx, src/components/controllers/page.jsx, src/components/controllers/tutorial-page.jsx, src/components/header/index.jsx, src/lib/use-content.js
We have a couple of markdown docs that differ in naming to the URL path, namely `/` -> `index.md` && `/tutorial` -> `/tutorial/index.md`
As the diff shows, this was previously handled at point of use, so the header had to correct paths, route components had to correct the paths, etc., and in this case `<ContentRegion>` was missing it so some links would 404 (`/tutorial.json`/`tutorial.md` doesn't exist). Better to handle this internally to `prefetchContent`/`useContent` as we can consistently apply the remapping & keep it all in one place.
=> refactor: Extract content paths util

content/en/guide/v10/preact-iso.md, src/config.json
"Router" has been the #1 search term for our docsearch every week since I got access ~4 months ago, with "route" and "location" also usually appearing in the top 10. Right now "router" links to a single reference of `preact-router` we have in the v8 upgrading docs which I don't think is offering users much value or what they're looking for. As such, I feel that we should offer some information here to get users started with routing as it's clearly a sought-after topic.
I've created a new section in the sidebar to accommodate this, thinking we can perhaps add more of our libraries and tools in the future. For example, `prefresh`, `@preact/preset-vite`, etc. I figure it shouldn't be too hard to keep in-sync, it's just a copy/paste of the readme for now.
=> docs: Add preact-iso docs

src/components/splitter/splitter.module.css
Interacting with the splitter component in the REPL/tutorial on mobile can be a bit fiddly at the moment as the page can scroll whilst the user is interacting with it. I'm over exaggerating it here but this video is a decent demonstration:
https://github.com/user-attachments/assets/1ae0545a-ec00-4c6a-a487-0bc341166681
Easy fix however, just need to set `touch-action` to `none` to disable standard pan/zoom touch interactions whilst the user is interacting with the splitter.
=> fix: Disable touch actions when interacting w/ splitter component

src/components/controllers/repl/index.jsx, src/components/splitter/index.jsx
The two vertical panes of the REPL makes it a bit tricky to use on mobile as the editor is only wide enough to display 15-20 characters at standard zoom (experience may vary a bit).
This PR adds a "auto" layout to the splitter, allowing it to determine the orientation depending on the screen size. Rather arbitrarily I've decided on 600px to be the cutoff point, anything less than that and the width is pretty punishing. As such, the REPL will now show as two stacked panes or two side-by-side panes depending on the width of the user's device which I think is a nice little improvement.
I've added a ResizeObserver too; not sure it's really needed, but saves from having to reload the page if the user does rotate orientation whilst the REPL is open. I figure it wouldn't be an unwelcome …
=> refactor: Rotate REPL to fit better on smaller screens (mobile)

src/assets/.well-known/traffic-advice, src/assets/_headers, src/assets/_redirects, vite.config.js
This PR tries to address some of the 404's we're seeing, fixing them where appropriate (see below for the Netlify stats). None of these should be impacting users though.
- `/content/*`
Not necessarily a problem, but caused by the `/content/*` -> `/content/*` redirect we have (created in #371). Not quite sure about the original purpose, something to do with Netlify's serving of markdown, but we don't serve markdown anymore and this kinda screws with the stats.
Every missing translation gets redirected to `/content/*` which itself just 404s as it's a nonsense URL. We have existing fallback methods to handle this though, both for content fetching & routing, so we can just remove the redirect. As such, all of those requests will still 404 as they're legitimate requests for translations we …
=> chore: Address some 404's

content/zh/tutorial/01-vdom.md, content/zh/tutorial/03-components.md, content/zh/tutorial/04-state.md, content/zh/tutorial/05-refs.md, content/zh/tutorial/06-context.md, content/zh/tutorial/07-side-effects.md, content/zh/tutorial/08-keys.md, content/zh/tutorial/09-error-handling.md
This PR adds translated Chinese versions of several tutorial files in the Preact documentation. By providing these translated materials, it makes it easier for Chinese - speaking users to learn Preact through step - by step
Previously, the Chinese documentation might have lacked detailed and up - to - date tutorial content, which could be a barrier for Chinese users to quickly understand and master Preact. This PR addresses this issue by adding Chinese translations of key tutorial sections, helping Chinese users to learn Preact more effectively without having to rely solely on the English documentation.
File Addition: Added seven new Markdown files in the directory. These files are translations of the corresponding English tutorial files, including step tutorials 03-09.
Translation Work: …
=> docs[translate] translate zh docs from en version in turorial

content/zh/guide/v10/context.md, content/zh/guide/v10/debugging.md, content/zh/guide/v10/forms.md, content/zh/guide/v10/getting-started.md, content/zh/guide/v10/hooks.md, content/zh/guide/v10/preact-iso.md, content/zh/guide/v10/preact-testing-library.md, content/zh/guide/v10/refs.md, content/zh/guide/v10/server-side-rendering.md, content/zh/guide/v10/signals.md, content/zh/guide/v10/tutorial.md, content/zh/guide/v10/typescript.md, content/zh/guide/v10/unit-testing-with-enzyme.md, content/zh/guide/v10/upgrade-guide.md, content/zh/guide/v10/web-components.md, content/zh/guide/v10/whats-new.md, src/components/controllers/guide-page.jsx
This PR aims to synchronize the Chinese translation documents with the English documentation in the guide.
1.Added previously untranslated files by the community.
2.Corrected outdated content in the current Chinese documentation.
3.Marked the existing Chinese documentation as "under maintenance" and synchronized its English translation.
According to the contributor guidelines, the preact-www project was built, and the pages were checked to ensure the usability of the modified parts.
=> Docs[Translate] Update and Revise Chinese Guide Translations

content/en/guide/v10/server-side-rendering.md
Re: https://x.com/transpiracy/status/1928117408180429291
In addition to adding mention of the streaming exports, I tried to split the page into sections, make our code examples a bit more focused & consistent, stylistically, and fixed some of the examples for the `/jsx` mode as some were fairly out of date.
My brain is struggling to write tonight though, suggestions very welcome! In particular I'm not sure if we want to provide any commentary about when one should use rts vs the streaming variants given the massive amount of nuance there, though nothing at all might confuse users.
=> docs: Rewrite most of our SSR doc, add streaming mentions

content/en/guide/v10/signals.md
Mostly a direct copy/paste of the new signal util docs with only the `useSignalRef` example getting fleshed out a bit more as I think it's useful to concretely show how it can double as both a ref (attaching to DOM nodes) and a signal (auto-tracked by `useSignalEffect`).
I also added specific sub-sections for existing hooks; we've had a lot of people over the years not realize these even existed when getting started as they were only mentioned in footnotes beneath the core APIs. Way too easy to miss. Also gives us something to link to when needed.
=> docs: Add mention of new signal utils

plugins/generate-llms-txt.js, plugins/precompile-markdown/index.js, src/lib/frontmatter.js, vite.config.js
This will enable the creation of a Preact/signals MCP and so on
=> Generate llms.txt file

content/de/about/demos-examples.md, content/de/about/libraries-addons.md, content/en/about/demos-examples.md, content/en/about/libraries-addons.md, content/es/about/demos-examples.md, content/es/about/libraries-addons.md, content/fr/about/demos-examples.md, content/fr/about/libraries-addons.md, content/kr/about/demos-examples.md, content/kr/about/libraries-addons.md, content/pt-br/about/demos-examples.md, content/pt-br/about/libraries-addons.md, content/ru/about/demos-examples.md, content/ru/about/libraries-addons.md, content/tr/about/demos-examples.md, content/tr/about/libraries-addons.md, content/zh/about/demos-examples.md, content/zh/about/libraries-addons.md
Purely just clean up/consistency issues:
- `marked` at some point stopped supporting markdown formatting within links (`**`, `__`, etc). Seems to have been years ago though as some links were formatted correctly, others were not.
- `**Preact Website** _(preactjs.com)_` is currently displayed like this on the site
- We were using two spaces at the end of content to for a line break. This is a bit fiddly, and wasn't applied everywhere, so I've replaced with `<br>`
- Corrects capitalization of "GitHub"
Probably should go through all of these libs & examples to see which are still around, butt that's a task for another day
=> chore: Correct formatting of Demos & Libraries pages

src/assets/_redirects
Netlify, via our config here, is set up to redirect all 404'ing requests to `/404/index.html`, which isn't unreasonable for most pages but our "guess and check" method of fetching translated content makes this a bit wasteful. In the event of a missing translation file, all we do is read the status code & discard the response body, which is the prerendered 404 page (~3kb w/ gzip):
https://github.com/preactjs/preact-www/blob/4cf9283f21d364902d8a4aec492f0d399485dcdb/src/lib/content.js#L16-L18
We could (and perhaps should) build a content manifest to skip some of these needless fetches, in the meantime, we can return a smaller asset at the very least. Reduces data egress & is likely faster for Netlify to respond with.
=> refactor: Don't redirect json/content 404's to 404 page

src/components/header/search.jsx, src/style/docsearch.css
Instead of lazily loading Docsearch (which offers only a momentary delay in downloading the chunk as it's used in the header), let's lazily load it only upon intent to interact, i.e., upon focus, mouse over, touch start, etc. If they user interacts with the docsearch button prior to mount, we'll show a loading bar & trigger a click imperatively once it's loaded, getting around any "jank" issues where the user will need to submit another click/enter key (if tabbing), etc.
Cuts the initial JS load by about 47% or 28kb. Couple kbs less of CSS too, as that'll lazy load now as well.
=> refactor: Lazily load docsearch only on intent to interact

content/en/guide/v8/getting-started.md, src/components/blog-overview/index.jsx, src/components/header/index.jsx, src/components/header/style.module.css, src/components/sidebar/index.jsx, src/config.json, src/lib/cx.js, src/lib/i18n.jsx
Forewarning, sorry, this is fairly big.
Refactors most of the header to make everything a bit more fit for purpose but there are no real functional changes. It corrects a few (IMO) minor grievances that have popped up whilst making other edits:
- Our usage / needs have drifted over the years compared to when most of components were built. Plenty of this is my doing, but for example:
- Whilst we had a `<NavMenu>` for the "About" routes, we later added a language drop down. This overlapped somewhat with the drop-down menu, but not completely, so there's this [awkward ternary](https://github.com/preactjs/preact-www/blob/0d52a6d9397f4ad9dda77b48c6b6f8a16690816d/src/components/header/index.jsx#L160-L182) in the component.
- We needed to list `/branding` in `config.nav` so that it was detected …
=> refactor: Rebuild header components

src/lib/frontmatter.js
Updated the frontmatter regex to accept both LF and CRLF line endings, improving compatibility with Windows environments.
=> [fix]Support CRLF in frontmatter parsing

src/lib/frontmatter.js
Allowing CRLF line endings was the wrong move, we should not have them to begin with in the project:
https://github.com/preactjs/preact-www/blob/6bd66fbca9331e3ef4274f47e50e855fab41dd69/.editorconfig#L5
#1329 was just one of a handful of symptoms (#1331, #1332, #1333, #1334) stemming from the user's editor not adhering to our `.editorconfig`, causing a whole number of features to break apart at the seams. Reverting & requiring use of the config is the better path, IMO.
=> revert: #1329 as it's a symptom of another issue

.github/size-plugin.yml, .github/workflows/ci.yml, package-lock.json, package.json, vite.config.js
Might be useful for easier eyeballing of some PRs
=> ci: Try adding compressed-size-action for build stats
