content/about/libraries-addons.md
Fixes developit/preact-compat#18
=> Add shallow-compare

content/about/libraries-addons.md
=> Add preact-socrates & preact-token-input

content/guide/forms.md
See https://github.com/developit/preact/issues/241
=> Remove .preventDefault() in checkbox example

content/guide/switching-to-preact.md
=> Add switch guide

content/index.md, src/style/index.less
Implements #30 
I couldn't find or detect a CSS styleguide, so I just add a new class.
I removed link previous class because they were dead code.
=> Added white color to Getting started link

content/about/libraries-addons.md
I made preact-shallow-compare -> shallow-compare because it works for multiple react like libs. Updated the name and link.
=> Update link from preact-shallow-compare -> shallow-compare

content/guide/differences-to-react.md
Just fixes minor typo:
http://www.future-perfect.co.uk/grammar-tip/is-it-focussed-or-focused/
=> differences-to-react: fix typo

content/lang/zh/about/browser-support.md, content/lang/zh/about/demos-examples.md, content/lang/zh/about/libraries-addons.md, content/lang/zh/about/project-goals.md
Corrected the Chinese translation of the following files,Thx @lcxfs1991 point out!
1. zh/about/browser-support.md
2. zh/about/libraries-addons.md
3. zh/about/project-globals.md
4. zh/about/demo-examples.md
=> corrected chinese translation for 'about'

content/index.md
I'm not sure because I can't find the minified gzipped file you're referring to, but just in case you mean kilobytes (kB) not kilobits (kb), here's a patch to fix it.
=> Do you mean kilobytes instead of kilobits?

content/guide/forms.md
This will handle #54, I'm brand new to Preact but including `e.preventDefault()` in a click handler seems to cause some strange behaviors, at least in conjunction with Redux.
Cheers!
=> Remove the language referencing preventDefault()

src/components/footer/index.js
This PR updates Edit page link to support the new languages, just one step easier for new contributors.
Also, have you thought about support languages as URLs? It would increase shareability :)
=> Update Edit page link to support i18n

content/lang/pt-br/404.md, content/lang/pt-br/about/browser-support.md, content/lang/pt-br/about/demos-examples.md, content/lang/pt-br/about/libraries-addons.md, content/lang/pt-br/about/project-goals.md, content/lang/pt-br/about/we-are-using.md, content/lang/pt-br/guide/differences-to-react.md, content/lang/pt-br/guide/extending-component.md, content/lang/pt-br/guide/external-dom-mutations.md, content/lang/pt-br/guide/forms.md, content/lang/pt-br/guide/getting-started.md, content/lang/pt-br/guide/lifecycle-methods.md, content/lang/pt-br/guide/linked-state.md, content/lang/pt-br/guide/progressive-web-apps.md, content/lang/pt-br/guide/switching-to-preact.md, content/lang/pt-br/guide/types-of-components.md, content/lang/pt-br/index.md, src/config.json
Thanks for Preact - it's awesome! I decided to translate the website to PT-BR as a way to spread some love to OSS and give back to this incredible project!
Let me know if something needs fixing, I'll gladly update it! :D
=> Translated to Brazilian Portuguese 🇧🇷

content/lang/pt-br/index.md
As per the convo in #63, I reworded the headline to fit in a single line
=> Reworded 'a different kind of lib' in PT-BR to fit in a single line

content/lang/pt-br/index.md
Reworded the PT-BR headline to avoid it splitting into two lines - This time, for good! ;)
=> Reworded (again) the PT-BR headline to fit in a single line

content/lang/zh/guide/progressive-web-apps.md, content/lang/zh/index.md
=> add chinese transation of index.md

content/lang/zh/guide/progressive-web-apps.md, content/lang/zh/index.md
fix the the following files:
1. index.md
2.progressive-web-apps.md
=> fix the link format

content/guide/differences-to-react.md
Follow up from https://github.com/developit/preact/issues/460.
=> Add note about differences in context inheritance

content/lang/pt-br/index.md
There were a few typos that didn't break the meaning but were not nice to see
=> Fixes small typos to PT-BR homepage

content/lang/pt-br/guide/switching-to-preact.md
quando = when
quanto = as .. as ..
=> Fix wrong pt translation

content/about/demos-examples.md
reference: https://github.com/developit/preact/pull/510#issuecomment-272726562
=> add demo: preact-starter

content/about/demos-examples.md
whitespace got truncated; lost newline
=> fix line break

content/guide/forms.md
=> Use class property for event handler

content/lang/pt-br/guide/progressive-web-apps.md
Really small stuff 💅
repeat visits -> visitas repetidas
offiline -> offline
leva **a** maior tempo de carregamento, interpretação e análise. -> leva **a um** maior tempo de carregamento, interpretação e análise.
_Congrats for the docs in Portuguese!_
=> Fix small PT-BR 🇧🇷  typos

content/about/demos-examples.md
- Modified docs to add preact-minimal
=> Added preact-minimal to demos docs

content/about/libraries-addons.md
https://github.com/download/preact-helmet
=> Add link to preact helmet

content/lang/es/about/libraries-addons.md, content/lang/es/about/project-goals.md, content/lang/es/guide/differences-to-react.md, content/lang/es/guide/extending-component.md, content/lang/es/guide/external-dom-mutations.md, content/lang/es/guide/forms.md, content/lang/es/guide/getting-started.md, content/lang/es/guide/lifecycle-methods.md, content/lang/es/guide/linked-state.md, content/lang/es/guide/progressive-web-apps.md, content/lang/es/guide/switching-to-preact.md, content/lang/es/guide/types-of-components.md, content/lang/es/index.md
I also took the time to fix some typos and translation errors.
=> fix some typos and use neutral spanish [fix #90]

content/about/we-are-using.md, src/assets/instantdomainsearch.svg
=> Add Instant Domain Search

content/lang/zh/about/browser-support.md, content/lang/zh/about/demos-examples.md, content/lang/zh/about/libraries-addons.md, content/lang/zh/about/project-goals.md, content/lang/zh/about/we-are-using.md, content/lang/zh/guide/differences-to-react.md, content/lang/zh/guide/extending-component.md, content/lang/zh/guide/external-dom-mutations.md, content/lang/zh/guide/forms.md, content/lang/zh/guide/getting-started.md, content/lang/zh/guide/lifecycle-methods.md, content/lang/zh/guide/linked-state.md, content/lang/zh/guide/progressive-web-apps.md, content/lang/zh/guide/switching-to-preact.md, content/lang/zh/guide/types-of-components.md, content/lang/zh/index.md
1. Add space between Chinese characters and letters.
2. Replace all half-width punctuation by full-width punctuation.
3. Fix spelling mistakes.
4. Optimize expression.
5. Use more authentic statements.
=> doc: Optimize Chinese Document

content/lang/pt-br/about/demos-examples.md, content/lang/pt-br/about/libraries-addons.md, content/lang/pt-br/about/project-goals.md, content/lang/pt-br/about/we-are-using.md, content/lang/pt-br/guide/differences-to-react.md, content/lang/pt-br/guide/extending-component.md, content/lang/pt-br/guide/external-dom-mutations.md, content/lang/pt-br/guide/forms.md, content/lang/pt-br/guide/getting-started.md, content/lang/pt-br/guide/linked-state.md, content/lang/pt-br/guide/switching-to-preact.md, content/lang/pt-br/guide/types-of-components.md, content/lang/pt-br/index.md
- Fixing some typos
- Updating examples.
- Removing dead inks
- Updating linked state page for Preact 8
=> Updating PT-BR translation

content/about/libraries-addons.md
Add the unexpected-preact library to the testing section
=> Add unexpected-preact to testing

src/index.js
Just adds the exports to the global variable, I find it nice when library sites make themselves available in the console to tinker around with
=> Allow users to play with preact in the browser console

content/lang/es/guide/external-dom-mutations.md, content/lang/es/guide/linked-state.md, content/lang/es/index.md, content/lang/zh/guide/external-dom-mutations.md, content/lang/zh/index.md
- Remove dead links in ES and ZH
- Update linked state to Preact 8 in ES
I would really like to update linked state docs in Chinese, but I do not have as much skill in the language 🙇.
=> Update links and docs in ES and ZH

content/guide/progressive-web-apps.md
Hey hey, tech writer for Lighthouse here. Just stumbled on this little mention and figured I'd throw in a link :)
=> add link to Lighthouse

content/lang/es/about/we-are-using.md
Spanish we-are-using has missing content:
=> Update spanish we-are-using

content/about/libraries-addons.md
Preact-Fluid: Minimal UI kit for Preact Apps based on Styled Components
Github Link ---> https://github.com/ajainvivek/preact-fluid
=> Added GUI toolkit under libraries and addon

src/components/routes.js
=> Match param name to JSDoc

content/about/we-are-using.md, content/lang/de/about/we-are-using.md, content/lang/es/about/we-are-using.md, content/lang/fr/about/we-are-using.md, content/lang/pt-br/about/we-are-using.md, content/lang/tr/about/we-are-using.md, content/lang/zh/about/we-are-using.md
Took the help of Google Translate for the Chinese version of this page.
=> chore(we-are-using): Sync we-are-using page in all languages

content/about/libraries-addons.md, content/lang/de/about/libraries-addons.md
It's still very unfinished but I'm trying to complete it
=> Add PreactBoot to the libraries

content/about/demos-examples.md
`Code and Comment` is the application which add the comments to a file in Github.
This is built with Preact, unistore and preact-router.
demo: https://code-and-comment.github.io/code-and-comment/
repository: https://github.com/code-and-comment/code-and-comment
=> Add Code and Comment to Full Apps section in demos-examples.md

content/guide/switching-to-preact.md
see https://twitter.com/johnmosesman/status/1112527189038301185
=> Fix webpack.js.org alias link

content/lang/fr/index.md
Fixed typos and changed syntax. Rewrite some sentences to make them catchier.
=> Update french version of index.md

src/style/markdown.less
This PR fixes a visual regression that was introduced in #292 .
=> Fix weird looking github icons

preact.config.js, src/pwa.js
This just fixes the "empty style chunks" issue (100b JS files with an empty webpack module in them).
=> Tidyup Addendum

package.json, preact.config.js, src/components/footer/index.js
Automatically rotate through top contributors in footer instead of always putting my name.
=> Sharing Footer

content/index.md, src/components/app.js, src/components/header/index.js, src/components/header/style.less, src/components/jumbotron/style.less, src/components/logo.js, src/store.js, src/style/index.less, src/style/variables.less
This PR simplifies our header a bit to make it look "cleaner". I'll expect it to undergo more changes in the coming week, but this is a good starting point we can work on :+1:
=> Simplify Hero/Jumbotron

package-lock.json, package.json
This mainly removes the obnoxious browserlist warning.
=> Upgrade to preact-cli rc3

src/components/controllers/page/style.less, src/components/controllers/page/table-of-contents.less, src/components/footer/style.less, src/style/variables.less
=> Fix white borders around hero

content/index.md, content/lang/de/index.md, content/lang/es/index.md, content/lang/fr/index.md, content/lang/it/index.md, content/lang/pt-br/index.md, content/lang/tr/index.md, content/lang/zh/index.md, src/components/controllers/page/style.less, src/components/header/style.less, src/components/jumbotron/index.js, src/components/jumbotron/style.less, src/style/index.less, src/style/variables.less
- Add subtle gradients
- Add code sample right at the top
- Restyle corner
=> Change jumbotron/hero styling

src/components/controllers/page/index.js, src/components/controllers/page/style.less, src/components/controllers/page/table-of-content.js, src/components/controllers/page/table-of-contents.less, src/style/variables.less
- Previously the sidebar was bound to the table of contents
- Responsive improvements
- A few CSS cleanups while we're at it
=> Prepare sidebar for versioned docs

src/components/controllers/page/index.js, src/components/controllers/page/sidebar.js, src/components/controllers/page/sidebar.less, src/components/controllers/page/style.less, src/components/controllers/page/table-of-content.js, src/components/controllers/page/table-of-contents.less, src/components/doc-version/index.js, src/components/doc-version/style.less
- Adds doc version switcher in the sidebar
- Restructure sidebar to show version switcher (even on mobile)
- Add more spacing to TOC for touch-based interactions
=> Add doc version switcher (just UI)

src/components/controllers/page/sidebar.js, src/components/controllers/page/sidebar.less, src/components/controllers/page/style.less, src/components/controllers/page/table-of-content.js, src/components/controllers/page/table-of-contents.less, src/components/header/style.less, src/components/jumbotron/style.less, src/style/index.less
This PR contains lots of responsive fixes and minor design corrections.
=> Responsive overhaul

content/index.md, content/lang/de/index.md, content/lang/es/index.md, content/lang/fr/index.md, content/lang/it/index.md, content/lang/pt-br/index.md, content/lang/tr/index.md, content/lang/zh/index.md
Might be confusing for newcomers. See: https://mobile.twitter.com/sophiebits/status/1152629550511038464
=> Remove mutation from code examples

content/index.md
- Rewrite `closer to the metal` section (seemed to be misunderstood by users)
- Rewrite Performance section and remove `LinkedState` mentions.
=> Update home page content

src/lib/request.js
=> Fix incorrect status check

package-lock.json, package.json
=> Upgrade preact-cli

content/guide/v10/differences-to-react.md
This PR is based on #332 , which is why it is marked as a draft.
=> Rewrite differences to React page

content/guide/v10/debugging.md, src/config.json
Noticed that we don't have any page about debugging Preact, so I wrote one. It has a section about the devtools and explains the most common warnings in `preact/debug`.
=> Add page about debugging preact apps

content/guide/hooks.md, content/guide/v10/hooks.md, src/config.json
Did a small part first so I could verify if you like the structure I'm using.
=> (docs) - useState

src/components/controllers/page/index.js, src/components/controllers/page/sidebar-nav.less, src/components/controllers/page/sidebar.js, src/components/controllers/page/sidebar.less, src/components/controllers/page/style.less, src/components/edit-button/style.less, src/components/header/index.js, src/components/header/style.less, src/lib/toggle-overlay.js, src/style/index.less
- Fix sidebar not scrollable on mobile
- Slightly improve black bar on navigation because of the edit button.
=> Minor CSS fixes

content/lang/de/index.md, content/lang/es/index.md, content/lang/fr/index.md, content/lang/it/index.md, content/lang/pt-br/index.md, content/lang/tr/index.md, content/lang/zh/index.md, src/components/footer/style.less
- Fix wrong logo version for non-english home page
- Remove left border on language selector (was an oversight from an earlier PR)
=> Invert logo

content/guide/v10/progressive-web-apps.md, content/guide/v8/progressive-web-apps.md, content/lang/de/guide/progressive-web-apps.md, content/lang/es/guide/progressive-web-apps.md, content/lang/fr/guide/progressive-web-apps.md, content/lang/pt-br/guide/progressive-web-apps.md, content/lang/tr/guide/progressive-web-apps.md, content/lang/zh/guide/progressive-web-apps.md
Regression caused by marked update in #355
=> Fix pwa doc inline html

.prettierignore, content/about/browser-support.md, content/about/cli.md, content/about/demos-examples.md, content/about/libraries-addons.md, content/about/project-goals.md, content/about/we-are-using.md, content/guide/v10/api-reference.md, content/guide/v10/components.md, content/guide/v10/context.md, content/guide/v10/debugging.md, content/guide/v10/differences-to-react.md, content/guide/v10/external-dom-mutations.md, content/guide/v10/forms.md, content/guide/v10/getting-started.md, content/guide/v10/hooks.md, content/guide/v10/progressive-web-apps.md, content/guide/v10/refs.md, content/guide/v10/server-side-rendering.md, content/guide/v10/switching-to-preact.md, content/guide/v10/tutorial.md, content/guide/v10/unit-testing-with-enzyme.md, content/guide/v10/upgrade-guide.md, content/guide/v10/web-components.md, content/index.md, src/components/controllers/page/index.js, src/components/header/style.less, src/style/index.less, src/template.html
- Add `meta.description` tags for SEO score
- Fix not enough contrast in header menu
- Fix not enough contrast in code-blocks with the `light` theme.
=> Improve lighthouse score further

content/en/guide/v10/upgrade-guide.md
Fixes https://github.com/preactjs/preact/issues/1843
=> Fix typo in `preact-portal` section

src/components/content-region.js, src/components/controllers/page/index.js, src/lib/content.js, src/template.html
Depends on #379 (retarget once merged).
Note: I split this out because I'm not sure if it's better or worse for performance. This PR will get a Netlify preview that we can use to compare against the one in #379 via webpagetest.org/easy.
=> Markdown worker

content/en/guide/v10/server-side-rendering.md
https://preactjs.com/guide/v10/server-side-rendering/#app
=> Fix docs typo: automtatically to automatically

content/en/guide/v10/web-components.md
This PR adds a little section about custom events on web components. See [this discussion](https://github.com/preactjs/preact/issues/1820) for the reason for this change.
=> Add section about custom events

content/en/guide/v10/getting-started.md, package-lock.json, package.json, src/components/controllers/repl/runner.js
Should just allow import through to unpkg at some point (maybe this is the solution for the iframe'd repl?), but for now this works.
=> fix HTM example

content/en/guide/v10/getting-started.md
Fixes https://github.com/preactjs/preact/issues/1881
=> Fix typo in getting started example

src/pwa.js
I set up exception tracking in prod and immediately started seeing errors that seem to be caused by this.
=> fix link handling bug

content/es/guide/v10/getting-started.md, content/es/guide/v8/getting-started.md
Add getting-started page in spanish lenguage for V10
=> Add getting-started page in spanish lenguage for V10

content/es/index.md
improvement to the Spanish language syntax
=> Improvement to the Spanish language syntax

content/en/guide/v10/forms.md
=> Fix incorrect JSX

content/en/guide/v10/progressive-web-apps.md
link to the working webpack code splitting link
=> fix the webpack code splitting doc link

content/en/guide/v10/tutorial.md
Not 100% sure if this is the correct tense, but the you is definitely missing there
=> Add missing word in tutorial.md

src/prerender.js
heh - was the translation. I can't remember if we prerender localized URLs, so for now I've just updated it to at least use the English versions.
Fixes #442.
=> fix [Object object] titles

content/en/guide/v10/api-reference.md
=> Remove incorrect return value from render doc

src/style/index.less
Fixed layout of buttons for small screens
**Current layout**
**Corrected layout**
=> Fixed layout of buttons for small screens

content/en/guide/v10/api-reference.md
=> Fix incorrect link target

src/lib/hydrator.js
=> Don't hydrate in dev mode

content/en/guide/v10/refs.md
This fixes Callback Refs section in refs.md.
=> Fix Callback Refs section in refs.md

content/pt-br/guide/v10/api-reference.md, content/pt-br/guide/v10/components.md, content/pt-br/guide/v10/context.md, content/pt-br/guide/v10/debugging.md, content/pt-br/guide/v10/differences-to-react.md, content/pt-br/guide/v10/extending-component.md, content/pt-br/guide/v10/external-dom-mutations.md, content/pt-br/guide/v10/forms.md, content/pt-br/guide/v10/getting-started.md, content/pt-br/guide/v10/hooks.md, content/pt-br/guide/v10/linked-state.md, content/pt-br/guide/v10/progressive-web-apps.md, content/pt-br/guide/v10/refs.md, content/pt-br/guide/v10/server-side-rendering.md, content/pt-br/guide/v10/switching-to-preact.md, content/pt-br/guide/v10/tutorial.md, content/pt-br/guide/v10/unit-testing-with-enzyme.md, content/pt-br/guide/v10/upgrade-guide.md, content/pt-br/guide/v10/web-components.md, content/pt-br/guide/v10/whats-new.md
Updating current pt-BR docs
sorry for the long PR @marvinhagemeister 
I just got some free time over the weekend and I thought it would be a good opportunity to start contributing to the project again.
=> Add v10 Translations for pt-BR

src/config.json
now the links are also translated =)
=> Adding navigation links translations for PT-BR

src/sw.js
This fixes #485 
/cc @prateekbh
=> Fix upgrades from the old website!

content/de/about/we-are-using.md, content/en/about/we-are-using.md, content/es/about/we-are-using.md, content/fr/about/we-are-using.md, content/pt-br/about/we-are-using.md, content/tr/about/we-are-using.md, content/zh/about/we-are-using.md
Here the link to the logo: https://static.swissdevjobs.ch/logo-images/swissdev-logo-name-square.png
=> Add SwissDev Jobs as a company using Preact

content/es/cli.md, content/es/cli/getting-started.md, content/es/cli/pre-rendering.md, content/es/cli/service-worker.md
=> Adding CLI pages translations

content/en/guide/v10/hooks.md
=> Tweaks for hooks documentation

src/components/jumbotron/style.less
=> Make the purple diagonal a little less diagonal

content/en/guide/v10/hooks.md
Tried to be less technical in our description of that hook.
=> Some wording changes for useErrorBoundary

src/prerender.js, src/template.html
This adds description to Twitter card.
This is only English description, not multilingual.
https://deploy-preview-519--preactjs.netlify.com/guide/v10/getting-started
https://cards-dev.twitter.com/validator
=> Add description to Twitter card

src/prerender.js
This sets title according to package name to Twitter card.
https://deploy-preview-521--preactjs.netlify.com/cli
https://cards-dev.twitter.com/validator
=> Set title according to package name

content/es/about/browser-support.md, content/es/about/demos-examples.md, content/es/about/libraries-addons.md, content/es/about/project-goals.md, content/es/index.md, src/config.json
- Fixed some typos
- Added translations for nav bar items
- Updated some old texts
=> Update Spanish translation

content/en/guide/v10/options.md, src/config.json
=> Add documentation about option hooks

content/en/guide/v10/options.md
Not 100% sure but I'm thinking the linear listing might be easier to read than the tables. They got squished on mobile.
=> Update new options hooks docs

src/index.js
This PR allows users to inspect our site with the official Preact devtools extension.
=> Attach to new devtools

content/en/guide/v10/debugging.md
The devtools extension is now available in the edge store.
=> Add Edge download link

content/en/guide/v10/getting-started.md, src/components/controllers/repl/runner.js
=> Fix No Build Tools example

content/en/guide/v10/tutorial.md
Assuming the original author meant "we'll" instead of "well"
=> Add missing apostrophe

content/en/about/browser-support.md
=> Update browser support page

content/de/index.md, content/en/index.md, content/es/index.md, content/fr/index.md, content/it/index.md, content/pt-br/index.md, content/tr/index.md, content/zh/index.md, src/components/jumbotron/style.less, src/components/logo.js, src/style/buttons.less, src/style/home.less, src/style/index.less, src/style/variables.less
This PR makes some design adjustments to the main block on our starting page. The goal was to make it look a little more tidy and a little more modern (the latter being subjective). It's best illustrated via a screenshot or the deploy preview. Let me know what you think 👍
=> Tidy up home page jumbotron

src/style/buttons.less, src/style/index.less, src/style/variables.less
=> Fix unreadable secondary button in light mode

src/components/jumbotron/style.less
=> Suggestion: shadow behind homepage code sample

content/en/guide/v10/api-reference.md
I was fixing #495 and got carried away.
=> Some API Reference updates

src/components/controllers/page/sidebar-nav.js, src/components/header/index.js, src/components/header/style.less, src/lib/hydrator.js, src/style/index.less
This PR fixes a few instances I found where the site rendered some non-idea HTML. Only the `p`-tag error around `<toc>` and the invalid HTML rendered by Agolia remains.
=> Improve HTML semantics

src/style/markdown.less
=> Fix hard to read links in dark mode

content/de/guide/v8/api-reference.md, content/en/guide/v8/api-reference.md, content/fr/guide/v8/api-reference.md, content/pt-br/guide/v8/api-reference.md, content/tr/guide/v8/api-reference.md, content/zh/guide/v8/api-reference.md
Added the componentWillUpdate lifecycle method signature to docs.
=> add signature of componentWillUpdate to examplecomponent

content/en/guide/v10/tutorial.md, content/pt-br/guide/v10/tutorial.md
This was reported on slack today. Our little tutorial app would always reload on form submission.
=> Fix incorrect form submission in tutorial

src/components/controllers/page/campaigns/BlackLivesMatter.less, src/components/controllers/page/campaigns/black-lives-matter.jsx, src/components/controllers/page/index.js, src/components/controllers/page/sidebar-nav.less, src/components/controllers/page/sidebar.less, src/components/controllers/page/style.less, src/components/controllers/repl/style.less, src/components/edit-button/style.less, src/components/header/style.less, src/components/jumbotron/style.less, src/components/logo.js, src/style/buttons.less, src/style/index.less, src/style/variables.less, src/template.html
This PR adds a banner for the Black Lives Matter movement in the US.
=> Black lives matter

content/en/cli/service-worker.md
- changes for the new 3 line SW API
=> new SW API documentation

content/en/guide/v10/options.md
`options.event` has return value.
=> Fix content/en/guide/v10/options.md

package-lock.json, package.json, size-plugin-browser.json, size-plugin-ssr.json, src/sw.js, src/template.html
This includes @marvinhagemeister's #608, migrates to the new preact-cli SW API, and fixes a hydration issue caused by our template omitting `<script type="__PREACT_CLI_DATA__">`.
Fixes #605.
=> Update to latest & fixes

content/en/guide/v10/upgrade-guide.md
=> Fix wrong link in docs

src/components/controllers/repl/index.js
directly assign to state from props in constructor
=> fix repl link

content/en/guide/v10/getting-started.md
Also add missing commas, code formatting, etc.
=> Fix grammar and capitalization

src/components/header/search.js
=> Fix search not working on mobile

content/en/guide/v10/server-side-rendering.md, content/pt-br/guide/v10/server-side-rendering.md
=> Fix renderToString pretty example

src/components/controllers/page/sidebar-nav.js, src/components/controllers/page/sidebar-nav.less
They're not really useful imo, because there aren't that many entries to search through, that make it necessary to drill down more granuarily.
=> Remove sidebar heading accordions

src/components/content-region.js, src/components/content-region.less, src/components/controllers/page/index.js, src/components/controllers/page/style.less, src/components/footer/index.js, src/components/routes.js, src/config.json, src/lib/i18n.js, src/style/index.less, src/style/variables.less
This PR adds a navigation section to the bottom of a page to point to the next and previous page if available. This shall make the reading experience feel more continuous.
=> Add navigation at the bottom of doc pages

content/en/guide/v10/web-components.md, package-lock.json, package.json, src/components/controllers/repl/runner.js
- Update web components page
- Add `preact-custom-element` to repl
Note: The repl will complain about already registered custom elements on update. My plan is to move our repl to a sandboxed iframe in a follow-up PR.
=> Update web components page

content/en/guide/v10/preact-testing-library.md
I replaced some sentences with grammar errors, and added a better explanation of what Preact Testing Library does.
=> Fix intro text for Preact Testing Library guide

content/de/index.md, content/en/index.md, content/es/index.md, content/fr/index.md, content/it/index.md, content/pt-br/index.md, content/tr/index.md, content/zh/index.md
A full sentence receives an ending dot.
A title or statement does not get an ending dot.
An action request can get an exclamation mark.
You can also see this as a proposal.
=> Copy changes

content/en/guide/v10/hooks.md
"Thinking this looks a strange?" -> "Thinking this looks a little strange?"
=> Add missing word to hooks.md

content/en/guide/v10/web-components.md
There is `Creating a Web Component` section in `web-components.md`.
=> Improve web-components.md

content/en/guide/v10/web-components.md
Just some rewording and bulking out of the content.
=> Web Components content updates

content/en/guide/v10/preact-testing-library.md
=> Fix typo in preact-testing-library.md

content/ja/guide/v10/preact-testing-library.md
This resolves #659.
This is a improved and added version of English version.
I asked @eiiches for a review.
=> Add content/ja/guide/v10/preact-testing-library.md

src/lib/prism.js
I should have left a comment in that file - it's generated from the URL, but hand-edited to remove a bunch of stuff that doesn't apply in Workers. I also remove Prism's own Worker stuff, which is what was breaking in prod.
=> Fix Prism 1.22 update

content/en/guide/v10/typescript.md
There may be a more preferred way to do with the change in behavior in TSC, but I believe this is a reasonable iterative improvement as at least now the instructions will actually work, even if they perhaps aren't ideally laid out.
=> Fixes TypeScript documentation.

.github/CODEOWNERS, CONTRIBUTING.md, content/en/about/demos-examples.md
I dislike this comment.
https://github.com/preactjs/preact-www/pull/718#issuecomment-734302272
I think the people who comment like this will be marjority in the future.
Therefore, I leave from Preact.
Thank you so far.
Good luck.
=> Remove .github/CODEOWNERS

content/en/guide/v8/getting-started.md
=> fix: Correcting one of v8's Getting Started examples

content/en/guide/v10/typescript.md
Add babelrc example from @marvinhagemeister at https://github.com/preactjs/preact/issues/1256#issuecomment-439695352
=> TypeScript: Add babelrc example

content/en/guide/v10/getting-started.md
See: https://github.com/preactjs/preact-www/pull/778#discussion_r653665266
=> Remove preact-cli local install instruction

content/en/tutorial/07-side-effects.md
Thanks @dfabulich! (https://twitter.com/dfabu/status/1478458211145420800)
=> Fix tutorial ch7 erroring on load

src/style/buttons.less, src/style/index.less
=> fix responsiveness of the website

src/components/controllers/page/sidebar.module.less, src/components/header/index.js, src/components/header/style.module.less, src/template.html
=> Add banner to support Ukraine

src/components/controllers/tutorial/style.module.less, src/style/index.less, src/style/variables.less
=> fix: Update tutorial component style.module.less to lower the content height

content/en/guide/v10/web-components.md
Relates to https://github.com/preactjs/preact/issues/3485
=> add shadow-dom mention

content/zh/about/browser-support.md, content/zh/about/demos-examples.md, content/zh/tutorial/01-vdom.md
Update the content of about in Chinese documents
Translate the first chapter of the tutorial into Chinese
=> doc:Update Chinese Document

src/components/controllers/page/index.js, src/components/controllers/page/style.module.less, src/style/markdown.less
Additional suggestions for #867.
=> More aggressive v8 banner (additional suggestions)

src/components/code-editor/style.module.less, src/style/prism.css, src/style/variables.less
=> Match repl code style with prism snippets

src/components/controllers/repl/index.js, src/components/controllers/repl/style.module.less, src/components/controllers/tutorial/index.js, src/components/controllers/tutorial/style.module.less, src/components/splitter/index.js, src/components/splitter/splitter.less
This extracts the Splitter component from the tutorial to a reusable component. It supports both horizontal and vertical resizing. It's now used for both the tutorial and the repl.
https://user-images.githubusercontent.com/1062408/188281838-139c14e7-36e2-48df-bfec-07960e895a56.mp4
=> Extract panel resize feature into component

src/components/controllers/repl/index.js
This PR adds support for linking to specific query examples. Plan is to allow our documentation to link to it as sort of a playground or just to see how the full example works together.
Linking is currently done via a `?example=my-example` query param. Once you change an example, the param is removed and the code is treated as if you had written it from scratch. It is then synced into `LocalStorage` like usual and retrieved on reload.
1. Check `?example` param
2. Check `localStorage`
3. Default to first available example
https://user-images.githubusercontent.com/1062408/188320521-5b2630c1-1a43-4a25-9fa8-9f6cbdb50b86.mp4
=> Add support for linking to REPL examples

src/components/controllers/repl/examples/context.txt, src/components/controllers/repl/examples/counter-with-htm.txt, src/components/controllers/repl/examples/github-repo-list.txt, src/components/controllers/repl/examples/simple-counter.txt, src/components/controllers/repl/examples/spiral.txt, src/components/controllers/repl/examples/todo-list.txt, src/components/controllers/repl/repl.worker.js
These were broken by #884 .
Also added the missing CSS for the spiral demo.
=> Fix repl examples

src/components/controllers/repl/examples/todo-list-signal.txt
=> Fix signal example

content/pt-br/cli.md
=> fix: Getting started with CLI link in pt-br

package-lock.json, package.json, preact.config.js, src/_headers, src/template.html
=> Add RSS feed

content/en/blog/signal-boosting.md
This pull request fixes an outdated variable name in signal-boosting.md.
=> Fix an outdated variable name in signal-boosting.md

content/en/blog/signal-boosting.md
This pull request fixes mistakes in a code example in the Signal Boosting blog post that a kind reader spotted.
=> Fix code example in signal-boosting.md

content/en/blog/signal-boosting.md
This pull request fixes a misleading code comment in signal-boosting.md.
=> Fix a code comment in signal-boosting.md

content/en/guide/v10/preact-testing-library.md
=> Add missing `waitFor` import

preact.config.js
Just adjusting a few things ahead of a CLI v4 publish.
=> chore: Refactor preact.config.js for consistency & stability

package-lock.json, package.json
=> Updates signals to latest.

content/es/guide/v10/getting-started.md, content/es/guide/v10/tutorial.md, content/es/guide/v10/upgrade-guide.md, content/es/guide/v10/whats-new.md
Description the changes:
I traslated to spanish the section Introduction
Checklist:
=> introduction section `traslated-spanish`

content/en/tutorial/08-keys.md
"second last" => "second to last"
=> Fix minor typo

content/en/tutorial/05-refs.md
=> Correct attribute for initial value of input field

content/es/blog/introducing-signals.md, src/config.json
**Was created the translated page for:** https://preactjs.com/blog/introducing-signals
=> es: Introducing Signals page

content/es/blog/introducing-signals.md, src/components/controllers/page/index.js
=> Add support for translation authors

content/en/guide/v10/server-side-rendering.md, content/ja/guide/v10/server-side-rendering.md, content/pt-br/guide/v10/server-side-rendering.md, content/zh/guide/v10/server-side-rendering.md
=> fix: Correct rts imports in pretty SSR examples

content/en/guide/v10/getting-started.md
Suggestions for language/verbiage welcome.
=> docs: Replace Preact-CLI suggestion with Vite

content/en/guide/v10/getting-started.md
Duplicated colons.
I've noticed it twice now so thought it was about time I corrected it.
=> chore: Fix typo

content/en/tutorial/01-vdom.md
=> docs: Add note on `render()` instantiation

content/en/guide/v10/preact-testing-library.md, content/ja/guide/v10/preact-testing-library.md
Fixes https://github.com/preactjs/preact/issues/4176
=> remove hooks testing lib

content/zh/blog/introducing-signals.md
=> docs: update zh/blog/introducing-signals.md

package.json
=> fix: Husky install

content/en/guide/v10/typescript.md
=> docs: Clarify TS transforms

content/en/about/demos-examples.md
Added a simple example of infinite scrolling
=> chore: add infinite scroll example

src/components/controllers/page/sidebar.module.css
Somehow missed this in my grep during #1067, sorry.
Pretty bad, sidebar can be opened but never closed.
=> fix: Sidebar on mobile

src/components/header/style.module.css, src/components/sponsors/style.module.css, src/components/we-are-using/style.module.css
=> chore: Fix CSS "error" and remove unused complex styles

src/components/header/index.jsx, src/lib/i18n.jsx
=> fix: Update root `lang` property upon changing language

content/zh/guide/v10/signals.md
fix markdown link & remove extra space.
=> chore(i18n): update zh-cn/guide/v10/signals

src/components/controllers/repl-page.jsx
Did this from my phone, should do the trick. I forgot we pass route props directly to the component w/ iso
=> fix: REPL shell & code query param

index.html, src/index.jsx
Path got screwed up in the Vite migration.
=> fix: Correct og:image path & extract it to HTML template

plugins/netlify.js, src/components/logo.jsx
=> fix: logo component type error and compatible with Windows

content/en/guide/v10/server-side-rendering.md
Need to add mention of streams yet, might tackle that later
=> feat: Add mention of rtsAsync to SSR page

content/en/guide/v10/typescript.md
=> docs: Add instructions for extending `InstrinsicElements` and `HTMLAttributes`

content/en/guide/v10/web-components.md
ref:
- https://github.com/preactjs/preact/issues/4418
=> Update web-components.md to explain camelCase vs dash-case props for custom elements

src/components/controllers/repl/examples/todo-lists/todo-list-signals.txt, src/components/controllers/repl/examples/todo-lists/todo-list.txt
Fixes https://github.com/preactjs/preact-www/pull/1164#discussion_r1739973537
Days since default button type has caused a mistake: ~~857~~ 0
=> fix: "Todo list" REPL examples

src/config.json
This pull request updates blogAuthors metadata for @developit, @rschristian, @marvinhagemeister, @JoviDeCroock and Yours Truly, based on Slack discussions.
=> chore: Update blogAuthors metadata

src/components/controllers/repl/repl.worker.js
=> REPL: Fix property access being considered non-side-effecting

src/components/header/search.jsx
Per #1106, it looks like I was doubting the value of lazy loading this. Certainly possible I was wrong to do so though.
=> refactor: Lazy load algolia docsearch

content/en/guide/v10/no-build-workflows.md
Mostly born out of this thread the other day: https://bsky.app/profile/passle.dev/post/3lfhkj2vpzk25
Not really sure how to tackle examples beyond a single HTML file yet as it quickly gets away from being Preact-focused, will have a think on that.
=> docs: Add HTM example to No-Build docs, reword some things

content/zh/guide/v10/no-build-workflows.md, src/config.json
Add Chinese translation of `guide/v10/no-build-workflows.md`.
=> docs: Add Chinese translation of no-build-workflows

content/pt-br/guide/v10/signals.md
create signal page pt-br translation
=> docs: create signal page pt-br translation

content/de/guide/v8/external-dom-mutations.md, content/en/guide/v10/external-dom-mutations.md, content/en/guide/v8/external-dom-mutations.md, content/es/guide/v8/external-dom-mutations.md, content/fr/guide/v8/external-dom-mutations.md, content/ja/guide/v10/external-dom-mutations.md, content/pt-br/guide/v10/external-dom-mutations.md, content/pt-br/guide/v8/external-dom-mutations.md, content/ru/guide/v10/external-dom-mutations.md, content/ru/guide/v8/external-dom-mutations.md, content/tr/guide/v8/external-dom-mutations.md, content/zh/guide/v8/external-dom-mutations.md
The domain has been taken over by a gambling site.
Fixes https://github.com/preactjs/preact-www/issues/1250
=> docs: remove webpackbin links

src/components/controllers/doc-page.jsx, src/components/controllers/style.module.css, src/lib/i18n.jsx
Re: #1256 
Introduces a sticky warning banner that warns users who view unmaintained translations (right now, everything but English & Russian). This warning banner provides a link to the English version as well as the sources here on GitHub in case any are willing to help contribute.
=> feat: Warn users for unmaintained translations

.github/workflows/ci.yml, .husky/pre-commit, package-lock.json, package.json, src/lib/repl.js, vite.config.js
=> chore: Bump most deps

content/zh/blog/preact-x.md
Recently, I've been reading The road to Preact 11 #2621 and Is Preact 11 dead? #4397, as well as the recent news about Remix v3 migrating to Preact. I believe the information in this blog is extremely important and valuable.
=> translator[docs] blog-preact-x.md to zh

content/zh/about/browser-support.md, content/zh/about/demos-examples.md, content/zh/about/libraries-addons.md, content/zh/about/project-goals.md, content/zh/blog/preact-x.md, content/zh/blog/prerendering-preset-vite.md, content/zh/blog/signal-boosting.md, content/zh/blog/simplifying-islands-arch.md, src/config.json
The translation work covers two scopes: about and blog. 
Currently, the Chinese documentation is basically consistent with the English documentation.
=> docs[tanslate]:Translate the untranslated Chinese parts.

plugins/rss-feed.js
Few issues that I'll comment on below:
=> fix: RSS feed plugin

content/es/blog/signal-boosting.md
=> fix: Correct images paths in ES translation of 'Signal Boosting'

content/en/guide/v10/preact-iso.md, content/en/guide/v11/preact-iso.md
Adds:
- A note clarifying nested routing behavior
- Mention of the new "polyglot-utils", for use in other langs
- Mention of the `locationStub` util for server-side JS usage outside of our prerenderer
=> docs: Sync iso to readme
